#!/usr/bin/env python3
# -*- coding: utf-8 -*-


# ------------********------------ 

"""6 DJ Algo
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/i222070tabidahusmani/6-dj-algo.f475782d-b80b-45da-a192-12128a200fcb.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20251117/auto/storage/goog4_request%26X-Goog-Date%3D20251117T133121Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D5a13a2462f9a7c498c9a1cfa9f42bd0d5cc61e55057b9ee8e43f5fef8f3c279431d11106b8f3a698f07bca2fed92aae883f4ff7b4906641195175fa139fec0edfa04bd585f23fd43949edfbe030dfb53511154f3b62647bcc2abfbd6450ede3fbc1d8ef590895e40a522503604158fcdb6e1c7dd303b91bc6712247809cf191f45f4fa07eb24e3971322756f3436f86a24c86117b613a5c633e308501170113b301febc1a4f2a2aac997614d9e149dc8e35cdafd03b675e2918e98345b6df665ded2c482ef8163702880e280e395013107c978a1e8c1768433c2a463439407c5e055ce323c49e08295ce29e5d66ad0ac8148d52d91fd43acce13b984edc073b0

GPU-accelerated Empirical Evaluation: Deutsch–Jozsa (Noiseless) Algorithm – Quantum Baseline

"""

# ----------------------------------------------------------------------------------------------------------------
# GPU-accelerated Empirical Evaluation: Deutsch–Jozsa (Noiseless) Algorithm – Quantum Baseline
# GPU
# ----------------------------------------------------------------------------------------------------------------

# Notes: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# Code focuses on Performance, Scalability, Reliability, Carbon footprints
# Output folders are:
    #   Performance = runtime
    #   Scalability = growth of runtime as N increases (digits/bits).
    #   Reliability = success rate + dispersion across repetitions.
    #   Carbon footprints = derived *only* from PERFORMANCE totals
    #   (sum of successful wall-times), device power 65 Watts fixed for comparasion, PUE 1.2 fixed, 
    #   country carbon intensity (kg CO2/kWh). I did not use scalability or reliability results for CO2.

#      Carbon Data File: 
#      Uses ONLY Performance runtimes (not Scalability/Reliability), 
#      Placed on my Desktop Excel of country intensities "Filtered CO2 intensity 236 Countries.xlsx"
#      (CSV or XLSX; year column optional. I have selected --year-select latest.)
# ----------------------------------------------------------------------------------------------------------------

# ------------********------------ Imports

import os, sys, time, tracemalloc, pathlib, warnings, math
from dataclasses import dataclass
from typing import List, Tuple, Dict, Any
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed

# ============================================================
# ------------********------------  GPU Setup and Dependencies
# ============================================================
print("🔍 Checking GPU availability...")

HAS_GPU = False
cp = None

try:
    import cupy as cp
    # Test if GPU is available and working
    with cp.cuda.Device(0):
        # Simple test to verify GPU functionality
        test_array = cp.zeros(10, dtype=cp.float32)
        result = cp.sum(test_array)
        HAS_GPU = True
        print(f"✅ GPU detected: {cp.cuda.runtime.getDeviceProperties(0)['name'].decode()}")
        print(f"   Memory: {cp.cuda.Device().mem_info[1] / 1e9:.2f} GB")
        print(f"   Compute Capability: {cp.cuda.runtime.getDeviceProperties(0)['major']}.{cp.cuda.runtime.getDeviceProperties(0)['minor']}")
except ImportError:
    print("❌ CuPy not available, falling back to NumPy")
    import numpy as cp
except Exception as e:
    print(f"⚠️  GPU setup failed: {e}, falling back to NumPy")
    import numpy as cp

# If GPU failed, use NumPy
if not HAS_GPU:
    import numpy as cp
    print("🔄 Using NumPy (CPU) backend")

# Install required packages
#This code checks for required Python packages and installs any that are missing at runtime.
#It attempts silent installation via pip and reports failures without stopping execution.
#It then imports numerical, data analysis, and plotting libraries and configures matplotlib for non-interactive use.

def _ensure(pkgs: List[str]):
    import importlib, subprocess
    missing = []
    for p in pkgs:
        try:
            importlib.import_module(p)
        except ImportError:
            missing.append(p)
    if missing:
        print(f"[setup] Installing missing packages: {missing}")
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *missing])
        except Exception as e:
            print(f"[setup] Auto-install failed: {e}")

_ensure(["pandas", "matplotlib", "openpyxl", "psutil"])

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# GPU utility functions
#This function determines and returns the name of the compute device being used.
#It attempts to query GPU properties when a GPU is available, handling errors gracefully.
#It defaults to identifying the device as a CPU-based NumPy backend when no GPU is present.
def get_device_name() -> str:
    """Get current device name"""
    if HAS_GPU:
        try:
            return f"GPU: {cp.cuda.runtime.getDeviceProperties(0)['name'].decode()}"
        except:
            return "GPU: Unknown"
    return "CPU: NumPy"

def safe_gpu_cleanup():
    """Safely cleanup GPU memory"""
    if HAS_GPU:
        try:
            cp.get_default_memory_pool().free_all_blocks()
        except:
            pass

# Thread-safe GPU operations
#This code defines a global lock to ensure thread-safe access to GPU resources.
#It wraps the experiment execution in a mutex so only one thread can use the GPU at a time.
#It safely runs a single experiment by delegating to the underlying execution function.
_gpu_lock = threading.Lock()

def run_experiment_thread_safe(args):
    """
    Thread-safe GPU experiment runner.
    Uses a lock to prevent multiple threads from accessing GPU simultaneously.
    """
    n, seed, oracle_type = args
    with _gpu_lock:  # Ensure only one thread uses GPU at a time
        return _run_single_experiment(n, seed, oracle_type)


#This function contains the core logic for executing a single Deutsch–Jozsa experiment.
#It initializes a seeded random generator and 
#    constructs the appropriate oracle based on the oracle type.
#It enforces correct handling and labeling of constant versus balanced oracle cases.

def _run_single_experiment(n: int, seed: int, oracle_type: str) -> dict:
    """
    Core experiment logic - run single Deutsch-Jozsa experiment.
    FIXED: Correct measurement interpretation for constant oracles.
    """
    rng = np.random.default_rng(seed)

    if oracle_type == "CONSTANT":
        c = int(rng.integers(0, 2))
        oracle = oracle_constant_phase(c)
        true_label = "CONSTANT"
    elif oracle_type == "BALANCED":
        s = np.zeros(n, dtype=np.uint8)
        while not s.any():
            s = rng.integers(0, 2, size=n, dtype=np.uint8)
        oracle = oracle_parity_phase(s)
        true_label = "BALANCED"
    else:
        raise ValueError("oracle_type must be CONSTANT or BALANCED")

    # --- Ideal DJ circuit, statevector ---

    tracemalloc.start()
    t0 = time.perf_counter()

    st = prepare_zero_state(n)         # |0^n>
    apply_h_layer(st, n)               # H^n
    oracle(st, n)                      # phase oracle (-1)^{f(x)}
    apply_h_layer(st, n)               # H^n

    runtime = time.perf_counter() - t0
    _, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    # FIXED: Correct measurement logic
    # For DJ algorithm:
    # - CONSTANT: all amplitude concentrates at |0^n⟩, so |amplitude[0]|² ≈ 1
    # - BALANCED: amplitude at |0^n⟩ is 0, so |amplitude[0]|² ≈ 0

    # Get amplitude at |0^n⟩ position
    amp_zero = st[0]
    # Compute probability (magnitude squared)
    if HAS_GPU and isinstance(st, cp.ndarray):
        p_zero = float(cp.abs(amp_zero) ** 2)
    else:
        p_zero = float(np.abs(amp_zero) ** 2)

    # Decision threshold: if probability at |0^n⟩ is close to 1, it's CONSTANT
    # if it's close to 0, it's BALANCED
    if p_zero > 0.5:  # More than 50% probability at |0^n⟩
        pred = "CONSTANT"
    else:
        pred = "BALANCED"

    correct = (pred == true_label)

    # Cleanup GPU memory
    safe_gpu_cleanup()

    return {
        "n": n,
        "seed": seed,
        "oracle": true_label,
        "prediction": pred,
        "correct": bool(correct),
        "queries_used": 1,
        "runtime_s": float(runtime),
        "peak_mem_mb": float(peak / (1024 ** 2)),
        "device": get_device_name()
    }


    #This function implements the core Deutsch–Jozsa experiment for a single run.
#It uses a seeded random number generator to 
    #   reproducibly create constant or balanced oracles.
#It validates the oracle type and assigns the correct ground-truth label for evaluation.

def _run_single_experiment(n: int, seed: int, oracle_type: str) -> dict:
    """
    Core experiment logic - run single Deutsch-Jozsa experiment.
    FIXED: Correct measurement interpretation for constant oracles.
    """
    rng = np.random.default_rng(seed)

    if oracle_type == "CONSTANT":
        c = int(rng.integers(0, 2))
        oracle = oracle_constant_phase(c)
        true_label = "CONSTANT"
    elif oracle_type == "BALANCED":
        s = np.zeros(n, dtype=np.uint8)
        while not s.any():
            s = rng.integers(0, 2, size=n, dtype=np.uint8)
        oracle = oracle_parity_phase(s)
        true_label = "BALANCED"
    else:
        raise ValueError("oracle_type must be CONSTANT or BALANCED")

    # -------------------- Ideal DJ circuit, statevector ---
    tracemalloc.start()
    t0 = time.perf_counter()

    st = prepare_zero_state(n)         # |0^n>
    apply_h_layer(st, n)               # H^n
    oracle(st, n)                      # phase oracle (-1)^{f(x)}
    apply_h_layer(st, n)               # H^n

    runtime = time.perf_counter() - t0
    _, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    # FIXED: Correct measurement logic
    # For DJ algorithm:
    # - CONSTANT: all amplitude concentrates at |0^n⟩, so |amplitude[0]|² ≈ 1
    # - BALANCED: amplitude at |0^n⟩ is 0, so |amplitude[0]|² ≈ 0

    # Get amplitude at |0^n⟩ position
    amp_zero = st[0]
    # Compute probability (magnitude squared)
    if HAS_GPU and isinstance(st, cp.ndarray):
        p_zero = float(cp.abs(amp_zero) ** 2)
    else:
        p_zero = float(np.abs(amp_zero) ** 2)

    # Decision threshold: if probability at |0^n⟩ is close to 1, it's CONSTANT
    # if it's close to 0, it's BALANCED
    if p_zero > 0.5:  # More than 50% probability at |0^n⟩
        pred = "CONSTANT"
    else:
        pred = "BALANCED"

    correct = (pred == true_label)

    # Cleanup GPU memory
    safe_gpu_cleanup()

    return {
        "n": n,
        "seed": seed,
        "oracle": true_label,
        "prediction": pred,
        "correct": bool(correct),
        "queries_used": 1,
        "runtime_s": float(runtime),
        "peak_mem_mb": float(peak / (1024 ** 2)),
        "device": get_device_name()
    }
def _run_single_experiment(n: int, seed: int, oracle_type: str) -> dict:
    """
    Core experiment logic - run single Deutsch-Jozsa experiment.
    FIXED: Correct measurement interpretation for constant oracles.
    """
    rng = np.random.default_rng(seed)

    if oracle_type == "CONSTANT":
        c = int(rng.integers(0, 2))
        oracle = oracle_constant_phase(c)
        true_label = "CONSTANT"
    elif oracle_type == "BALANCED":
        s = np.zeros(n, dtype=np.uint8)
        while not s.any():
            s = rng.integers(0, 2, size=n, dtype=np.uint8)
        oracle = oracle_parity_phase(s)
        true_label = "BALANCED"
    else:
        raise ValueError("oracle_type must be CONSTANT or BALANCED")

    # ------------********------------  Ideal DJ circuit, statevector ---
    tracemalloc.start()
    t0 = time.perf_counter()

    st = prepare_zero_state(n)         # |0^n>
    apply_h_layer(st, n)               # H^n
    oracle(st, n)                      # phase oracle (-1)^{f(x)}
    apply_h_layer(st, n)               # H^n

    runtime = time.perf_counter() - t0
    _, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    # FIXED: Correct measurement logic
    # For DJ algorithm:
    # - CONSTANT: all amplitude concentrates at |0^n⟩, so |amplitude[0]|² ≈ 1
    # - BALANCED: amplitude at |0^n⟩ is 0, so |amplitude[0]|² ≈ 0

    # Get amplitude at |0^n⟩ position
    amp_zero = st[0]
    # Compute probability (magnitude squared)
    if HAS_GPU and isinstance(st, cp.ndarray):
        p_zero = float(cp.abs(amp_zero) ** 2)
    else:
        p_zero = float(np.abs(amp_zero) ** 2)

    # Decision threshold: if probability at |0^n⟩ is close to 1, it's CONSTANT
    # if it's close to 0, it's BALANCED
    if p_zero > 0.5:  # More than 50% probability at |0^n⟩
        pred = "CONSTANT"
    else:
        pred = "BALANCED"

    correct = (pred == true_label)

    # Cleanup GPU memory
    safe_gpu_cleanup()

    return {
        "n": n,
        "seed": seed,
        "oracle": true_label,
        "prediction": pred,
        "correct": bool(correct),
        "queries_used": 1,
        "runtime_s": float(runtime),
        "peak_mem_mb": float(peak / (1024 ** 2)),
        "device": get_device_name()
    }

# ------------********------------ 
# Minimal statevector simulator (GPU-accelerated) 
# ------------********------------ 

#def hadamard_on_qubit applies a Hadamard gate to a selected qubit 
#   with support for GPU and CPU execution paths.
#It checks whether the state resides on the GPU and 
#   chooses the appropriate computation method.
#It updates the quantum state in place by 
#   combining amplitude pairs using normalized sums.

def hadamard_on_qubit(state, q: int, n: int):
    """Apply H on qubit q (little-endian bit ordering). GPU-accelerated."""
    dim = state.shape[0]
    m = 1 << q          # block size
    stride = m << 1
    inv_sqrt2 = 1.0 / math.sqrt(2.0)

    if HAS_GPU and isinstance(state, cp.ndarray):
        # GPU vectorized version
        for base in range(0, dim, stride):
            i0 = base
            i1 = base + m
            for off in range(m):
                a = state[i0 + off]
                b = state[i1 + off]
                state[i0 + off] = (a + b) * inv_sqrt2
                state[i1 + off] = (a - b) * inv_sqrt2
    else:
        # CPU version
        for base in range(0, dim, stride):
            i0 = base
            i1 = base + m
            for off in range(m):
                a = state[i0 + off]
                b = state[i1 + off]
                state[i0 + off] = (a + b) * inv_sqrt2
                state[i1 + off] = (a - b) * inv_sqrt2


#This function def z_on_qubit () applies a Z gate to a specified qubit with support for both GPU and CPU arrays.
#It creates an index mask to identify amplitudes where the target qubit is set.
#It flips the sign of those amplitudes in place using the appropriate backend.

def z_on_qubit(state, q: int):
    """Apply Z on qubit q: multiply amplitudes with bit(q)==1 by -1. GPU-accelerated."""
    dim = state.shape[0]
    bit = 1 << q

    if HAS_GPU and isinstance(state, cp.ndarray):
        # GPU vectorized version
        idx = cp.arange(dim, dtype=cp.uint64)
        mask = (idx & bit) != 0
        state[mask] = -state[mask]
    else:
        # CPU version
        idx = np.arange(dim, dtype=np.uint64)
        mask = (idx & bit) != 0
        state[mask] = -state[mask]



#def prepare_zero_state(n: int): initializes an n-qubit quantum state in 
#  the all-zero basis with optional GPU support.
#It allocates the state vector on the GPU or CPU depending on availability.
#It sets the first amplitude to one and returns the prepared state.
def prepare_zero_state(n: int):
    """Prepare |0^n> state. GPU-accelerated."""
    if HAS_GPU:
        st = cp.zeros(1 << n, dtype=cp.complex128)
    else:
        st = np.zeros(1 << n, dtype=np.complex128)
    st[0] = 1.0
    return st

def apply_h_layer(state, n: int):
    """Apply H⊗n. GPU-accelerated."""
    for q in range(n):
        hadamard_on_qubit(state, q, n)

# ========================= DJ phase-oracle (promised family) =========================
# ------------********---------------------********--------------********------------ 
# ========================= DJ phase-oracle (promised family) =========================


#This function  def oracle_constant_phase () creates a phase oracle for a constant Boolean function.
#It returns an inner function that applies a global phase flip when c equals one.
#It models constant Deutsch–Jozsa oracles via uniform state sign inversion.
def oracle_constant_phase(c: int):
    """
    Phase oracle for constant f(x)=c:
      c=0 -> identity; c=1 -> global phase (-1)
    """
    def apply(state, n: int):
        if c & 1:
            state *= -1.0
    return apply


#The function oracle_parity_phase defines a corrected balanced parity phase oracle 
# for the Deutsch Jozsa algorithm.
#It computes the parity s·x for each basis state and applies a corresponding phase flip.
#It supports both GPU and CPU execution paths using vectorized operations.

def oracle_parity_phase(s_bits: np.ndarray):
    """
    CORRECTED: Balanced parity oracle for f(x) = s·x mod 2
    Applies phase (-1)^(s·x) to each basis state |x⟩
    """
    s = s_bits.astype(np.uint8)
    def apply(state, n: int):
        dim = state.shape[0]
        # Apply phase based on parity: (-1)^(s·x)
        if HAS_GPU and isinstance(state, cp.ndarray):
            # GPU vectorized version
            indices = cp.arange(dim, dtype=cp.uint64)
            # Compute s·x for each x
            parity = cp.zeros(dim, dtype=cp.uint8)
            for i in range(n):
                if s[i]:
                    parity ^= ((indices >> i) & 1).astype(cp.uint8)
            # Apply phase: multiply by (-1)^parity
            phase = 1 - 2 * parity.astype(cp.float64)
            state *= phase.astype(cp.complex128)
        else:
            # CPU version
            indices = np.arange(dim, dtype=np.uint64)
            parity = np.zeros(dim, dtype=np.uint8)
            for i in range(n):
                if s[i]:
                    parity ^= ((indices >> i) & 1).astype(np.uint8)
            phase = 1 - 2 * parity.astype(np.float64)
            state *= phase.astype(np.complex128)
    return apply

# ------------********------------ 
# ============================== Carbon I/O ==========
# ------------********------------ 

# func def resolve_excel_path
def resolve_excel_path(excel_arg: str) -> str:
    p = pathlib.Path(excel_arg)
    if p.is_absolute() and p.exists():
        return str(p)
    desktop = pathlib.Path.home() / "Desktop" / excel_arg
    return str(desktop if desktop.exists() else p)

def load_carbon_excel(path: str, year_select: str = "latest") -> pd.DataFrame:
    df = pd.read_excel(path)
    cols = {c.lower(): c for c in df.columns}
    cand_country = next((v for k, v in cols.items() if "country" in k or "nation" in k or k == "location"), None)
    if cand_country is None:
        raise ValueError("No 'Country' column found.")
    cand_year = next((v for k, v in cols.items() if "year" in k or "date" in k), None)
    cand_intensity = next((v for k, v in cols.items()
                           if "intensity" in k or ("co2" in k and "kwh" in k) or "kgco2" in k or "gco2" in k), None)
    if cand_intensity is None:
        numeric_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
        if cand_year in numeric_cols:
            numeric_cols.remove(cand_year)
        if not numeric_cols:
            raise ValueError("No numeric intensity column detected.")
        cand_intensity = numeric_cols[0]
    keep = [cand_country] + ([cand_year] if cand_year else []) + [cand_intensity]
    df = df[keep].copy()
    df.columns = ["Country", "Year", "Intensity"] if len(keep) == 3 else ["Country", "Intensity"]
    if "Year" in df.columns and year_select.lower() == "latest":
        df = df.sort_values(["Country", "Year"]).groupby("Country", as_index=False).tail(1)

    # Heuristic unit fix: if median looks like g/kWh, convert to kg/kWh
    med = float(df["Intensity"].dropna().median())
    if med > 50:
        df["Intensity"] = df["Intensity"] / 1000.0

    return df.dropna(subset=["Country", "Intensity"]).reset_index(drop=True)

def compute_carbon(perf_df: pd.DataFrame, intensity_df: pd.DataFrame,
                   power_watts: float, pue: float, combine: bool) -> tuple[pd.DataFrame, pd.DataFrame]:
    total_runtime_s = float(perf_df["runtime_s"].sum())
    kWh_total = power_watts * pue * total_runtime_s / 3_600_000.0
    df = intensity_df.copy()
    df["kWh"] = kWh_total
    df["kgCO2e"] = df["Intensity"] * df["kWh"]

    # will return country-wise results
    carbon_output = df.sort_values("kgCO2e", ascending=False)

    summary = pd.DataFrame({
        "total_runtime_s": [total_runtime_s],
        "power_watts": [power_watts],
        "PUE": [pue],
        "kWh_total": [kWh_total],
        "median_intensity_kg_per_kWh": [float(df["Intensity"].median())],
        "mean_kgCO2e_across_countries": [float(df["kgCO2e"].mean())],
        "device": [perf_df["device"].iloc[0] if "device" in perf_df.columns else "Unknown"],
        "combine_mode": [combine],
        "countries_analyzed": [len(df)]
    })
    return carbon_output, summary

# ------------********------------ 
# ============================== Plot Helpers 
# ------------********------------ 

plt_kwargs = dict(dpi=140, bbox_inches="tight")

def _boxplot_with_labels(data, labels):
    # Matplotlib 3.9 renamed 'labels' -> 'tick_labels'
    try:
        plt.boxplot(data, tick_labels=labels)
    except TypeError:
        plt.boxplot(data, labels=labels)

def plot_performance(df: pd.DataFrame, outdir: str):
    g = df.groupby("n")["runtime_s"].mean().reset_index()
    plt.figure()
    plt.plot(g["n"], g["runtime_s"], marker="o", linewidth=2, markersize=8)
    plt.title(f"Performance: Runtime vs Input Size\n{get_device_name()}")
    plt.xlabel("Input Size n (bits)")
    plt.ylabel("Runtime (s)")
    plt.grid(True)
    plt.savefig(os.path.join(outdir, "perf_runtime_vs_n.png"), **plt_kwargs)
    plt.close()

    g2 = df.groupby("n")["queries_used"].mean().reset_index()
    plt.figure()
    plt.plot(g2["n"], g2["queries_used"], marker="s", linewidth=2, markersize=8)
    plt.title(f"Performance: Mean Queries vs n (DJ = 1)\n{get_device_name()}")
    plt.xlabel("Input Size n (bits)")
    plt.ylabel("Mean Queries Used")
    plt.grid(True)
    plt.savefig(os.path.join(outdir, "perf_queries_vs_n.png"), **plt_kwargs)
    plt.close()

def plot_scalability(df: pd.DataFrame, outdir: str):
    g = df.groupby("n")["peak_mem_mb"].mean().reset_index()
    plt.figure()
    plt.plot(g["n"], g["peak_mem_mb"], marker="^", linewidth=2, markersize=8, color='green')
    plt.title(f"Scalability: Memory vs Input Size\n{get_device_name()}")
    plt.xlabel("Input Size n (bits)")
    plt.ylabel("Memory (MB)")
    plt.grid(True)
    plt.savefig(os.path.join(outdir, "scal_memory_vs_n.png"), **plt_kwargs)
    plt.close()

    g2 = df.groupby("n")["runtime_s"].mean().reset_index()
    plt.figure()
    plt.loglog(g2["n"], g2["runtime_s"], marker="o", linewidth=2, markersize=8)
    plt.title(f"Scalability: Runtime (log-log)\n{get_device_name()}")
    plt.xlabel("n")
    plt.ylabel("Runtime (s)")
    plt.grid(True, which="both")
    plt.savefig(os.path.join(outdir, "scal_loglog_runtime.png"), **plt_kwargs)
    plt.close()

def plot_reliability(df: pd.DataFrame, outdir: str):
    data = [df[df["n"] == n]["queries_used"].values for n in sorted(df["n"].unique())]
    plt.figure()
    _boxplot_with_labels(data, labels=sorted(df["n"].unique()))
    plt.title(f"Reliability: Queries Distribution by n\n{get_device_name()}")
    plt.xlabel("Input Size n (bits)")
    plt.ylabel("Queries Used")
    plt.grid(True)
    plt.savefig(os.path.join(outdir, "rel_queries_boxplot.png"), **plt_kwargs)
    plt.close()

    g = df.groupby("n")["correct"].mean().reset_index()
    plt.figure()
    plt.plot(g["n"], g["correct"], marker="o", linewidth=2, markersize=8)
    plt.title(f"Reliability: Success Rate vs n\n{get_device_name()}")
    plt.xlabel("n")
    plt.ylabel("Success Rate")
    plt.grid(True)
    plt.savefig(os.path.join(outdir, "rel_success_vs_n.png"), **plt_kwargs)
    plt.close()

def plot_carbon(df: pd.DataFrame, combine: bool, outdir: str):

    # It will generate carbon footprint plots - country-wise
    # ------------********------------ Top 15 highest emissions
    top = df.nlargest(15, "kgCO2e")
    plt.figure(figsize=(12, 8))
    plt.barh(top["Country"][::-1], top["kgCO2e"][::-1], color='red', alpha=0.7)
    plt.xlabel("kg CO2e (higher = dirtier grid)", fontsize=12)
    plt.title(f"Carbon: Top 15 Highest Emissions\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(outdir, "carbon_top15.png"), **plt_kwargs)
    plt.close()

    # ------------********------------  Bottom 15 lowest emissions
    bot = df.nsmallest(15, "kgCO2e")
    plt.figure(figsize=(12, 8))
    plt.barh(bot["Country"][::-1], bot["kgCO2e"][::-1], color='green', alpha=0.7)
    plt.xlabel("kg CO2e (lower = cleaner grid)", fontsize=12)
    plt.title(f"Carbon: Bottom 15 Lowest Emissions\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(outdir, "carbon_bottom15.png"), **plt_kwargs)
    plt.close()

    # ------------********------------  Distribution histogram
    plt.figure(figsize=(10, 6))
    plt.hist(df["kgCO2e"], bins=30, alpha=0.7, edgecolor='black', color='orange')
    plt.xlabel("kg CO2e for this experiment", fontsize=12)
    plt.ylabel("Frequency", fontsize=12)
    plt.title(f"Carbon: Emission Distribution\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "carbon_distribution.png"), **plt_kwargs)
    plt.close()

    # ------------********------------ CDF plot
    xs = np.sort(df["kgCO2e"].values)
    ys = np.arange(1, len(xs) + 1) / len(xs)
    plt.figure(figsize=(10, 6))
    plt.plot(xs, ys, linewidth=2, color='purple')
    plt.xlabel("kg CO2e", fontsize=12)
    plt.ylabel("CDF", fontsize=12)
    plt.title(f"Carbon: Cumulative Distribution\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "carbon_cdf.png"), **plt_kwargs)
    plt.close()

# ============================== Utility Functions ==============================
#This utility function ensures that a given directory path exists by creating it if necessary.
#It provides a helper to write multiple pandas DataFrames into a single Excel file using separate sheets.
#It safely handles sheet naming limits while exporting tabular results.


def ensure_dir(d: str):
    """Ensure directory exists"""
    os.makedirs(d, exist_ok=True)

def to_excel(dfs: Dict[str, pd.DataFrame], path: str):
    """Save multiple DataFrames to Excel with different sheets"""
    with pd.ExcelWriter(path, engine="openpyxl") as w:
        for name, df in dfs.items():
            df.to_excel(w, index=False, sheet_name=name[:31])

# ============================== Main Experiment Runner ==============================

#This function (def run_dj_experiment()) serves as the main runner for Deutsch–Jozsa experiments
#     with fixed parameters suitable for a Kaggle environment.
#It configures experiment sizes, trial counts, resource settings, and 
#   prints a detailed runtime configuration summary.
#It creates required output directories and prepares balanced job lists for 
#    constant and balanced oracle experiments.

def run_dj_experiment():
    """
    Main Deutsch-Jozsa experiment runner with hardcoded parameters for Kaggle.
    Equivalent to: --sizes 6 8 10 12 --trials 10 --method dj
                   --device-power-watts 65 --pue 1.2 --combine
    """
    # Experiment parameters
    sizes = [6, 8, 10, 12]
    trials = 10  # trials per oracle type
    method = "dj"
    workers = 4  # Number of parallel threads

    # Carbon parameters
    device_power_watts = 65.0
    pue = 1.2
    combine = True

    print(f"🚀 Starting Deutsch-Jozsa experiments on {get_device_name()}")
    print(f"🔧 Configuration:")
    print(f"   Input sizes: {sizes}")
    print(f"   Trials per oracle type: {trials}")
    print(f"   Method: {method}")
    print(f"   Workers: {workers}")
    print(f"   Device power: {device_power_watts}W")
    print(f"   PUE: {pue}")
    print(f"   Combine carbon: {combine}")

    # Create output folders
    perf_dir = os.path.join(os.getcwd(), "Performance")
    scal_dir = os.path.join(os.getcwd(), "Scalability")
    rel_dir  = os.path.join(os.getcwd(), "Reliability")
    carb_root = os.path.join(os.getcwd(), "Carbon footprints")
    carb_dir  = os.path.join(carb_root, "carbon_by_country")

    for d in [perf_dir, scal_dir, rel_dir, carb_dir]:
        ensure_dir(d)

    # Prepare jobs - equal number of CONSTANT and BALANCED per n
    jobs = []
    for n in sizes:
        for i in range(trials):
            jobs.append((n, 1000 + 17 * n + i, "CONSTANT"))
            jobs.append((n, 2000 + 17 * n + i, "BALANCED"))

    all_rows = []

    def _consume(row):
        """Process completed job results"""
        all_rows.append(row)
        print(f"  ✅ n={row['n']}, oracle={row['oracle']}, seed={row['seed']} (runtime={row['runtime_s']:.6f}s, correct={row['correct']})")

    # Execute jobs with thread-based parallelization
    print(f"🔀 Running {len(jobs)} jobs in parallel with {workers} threads...")

    if workers > 1 and len(jobs) > 1:
        with ThreadPoolExecutor(max_workers=workers) as executor:
            # Submit all jobs
            future_to_job = {executor.submit(run_experiment_thread_safe, job): job for job in jobs}

            # Collect results as they complete
            for future in as_completed(future_to_job):
                try:
                    result = future.result()
                    _consume(result)
                except Exception as e:
                    job = future_to_job[future]
                    print(f"❌ Job failed n={job[0]}, seed={job[1]}, oracle={job[2]}: {e}")
    else:
        # Fallback to sequential execution
        for job in jobs:
            result = run_experiment_thread_safe(job)
            _consume(result)

    # Check if we have any successful results
    if not all_rows:
        print("❌ All jobs failed! Running sequentially as fallback...")
        for job in jobs:
            try:
                result = _run_single_experiment(job[0], job[1], job[2])
                _consume(result)
            except Exception as e:
                print(f"❌ Sequential fallback also failed for n={job[0]}, seed={job[1]}, oracle={job[2]}: {e}")

    if not all_rows:
        print("💥 CRITICAL: No experiments completed successfully!")
        return None

    perf_df = pd.DataFrame(all_rows)

    # ---------------- Performance Results ----------------
    print("📊 Generating Performance results...")
    perf_excel = os.path.join(perf_dir, "performance_results.xlsx")
    perf_agg = perf_df.groupby("n").agg({
        "runtime_s": "mean",
        "queries_used": "mean",
        "peak_mem_mb": "mean",
        "correct": "mean"
    }).reset_index()

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "raw_runs": perf_df,
            "aggregated": perf_agg
        }, perf_excel)

    plot_performance(perf_df, perf_dir)

    # ---------------- Scalability Results ----------------
    print("📈 Generating Scalability results...")
    scal_excel = os.path.join(scal_dir, "scalability_results.xlsx")
    scal_agg = perf_df.groupby("n").agg({
        "runtime_s": "mean",
        "peak_mem_mb": "mean",
        "queries_used": "mean"
    }).reset_index()

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "from_perf_runs": perf_df[["n", "seed", "oracle", "runtime_s", "peak_mem_mb", "queries_used"]],
            "aggregated": scal_agg
        }, scal_excel)

    plot_scalability(perf_df, scal_dir)

    # ---------------- Reliability Results ----------------
    print("🎯 Generating Reliability results...")
    rel_excel = os.path.join(rel_dir, "reliability_results.xlsx")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "correctness_analysis": perf_df[["n", "seed", "oracle", "prediction", "correct", "queries_used"]]
        }, rel_excel)

    plot_reliability(perf_df, rel_dir)

    # ---------------- Carbon Footprint Results ----------------
    print("🌍 Generating Carbon footprint results...")

    # Load carbon data from Kaggle input directory
    excel_path = "/kaggle/input/masters/Filtered CO2 intensity 236 Countries.xlsx"
    intensity_df = None

    try:
        # Try to load from the exact path
        intensity_df = pd.read_excel(excel_path)
        print(f"✅ Loaded carbon data from: {excel_path}")
        print(f"   Columns found: {list(intensity_df.columns)}")
        print(f"   Countries loaded: {len(intensity_df)}")

        # Auto-detect and process columns
        cols = {c.lower(): c for c in intensity_df.columns}
        cand_country = next((v for k,v in cols.items() if "country" in k or "nation" in k or k=="location"), None)
        if cand_country is None:
            raise ValueError("No 'Country' column found.")

        cand_intensity = next((v for k,v in cols.items() if "intensity" in k or ("co2" in k and ("kwh" in k or "/kwh" in k)) or "kgco2" in k or "gco2" in k), None)

        if cand_intensity is None:
            numeric_cols = [c for c in intensity_df.columns if pd.api.types.is_numeric_dtype(intensity_df[c])]
            if not numeric_cols:
                raise ValueError("No numeric intensity column detected.")
            cand_intensity = numeric_cols[0]

        # Keep only necessary columns
        intensity_df = intensity_df[[cand_country, cand_intensity]].copy()
        intensity_df.columns = ["Country", "Intensity"]

        # Convert gCO2/kWh to kgCO2/kWh if needed
        med = float(intensity_df["Intensity"].dropna().median())
        if med > 50:
            intensity_df["Intensity"] = intensity_df["Intensity"] / 1000.0

        intensity_df = intensity_df.dropna(subset=["Country", "Intensity"]).reset_index(drop=True)
        print(f"✅ Processed carbon data for {len(intensity_df)} countries")

    except Exception as e:
        print(f"❌ ERROR loading carbon data: {e}")
        print("💡 Using sample carbon data as fallback...")
        # Create sample data similar to other codes
        countries = ["France", "Sweden", "Norway", "Switzerland", "Austria", "Germany", "United States", "China", "India"]
        intensities = [52, 41, 32, 45, 62, 385, 389, 537, 708]
        intensity_df = pd.DataFrame({
            "Country": countries,
            "Intensity": [i/1000.0 for i in intensities]  # Convert to kg/kWh
        })

    ensure_dir(carb_dir)
    carbon_df, summary_df = compute_carbon(perf_df, intensity_df,
                                           power_watts=device_power_watts,
                                           pue=pue, combine=combine)
    carb_excel = os.path.join(carb_dir, "carbon_results.xlsx")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "carbon_results": carbon_df,
            "summary": summary_df,
            "intensity_input": intensity_df,
            "performance_reference": perf_df[["n", "seed", "runtime_s"]]
        }, carb_excel)

    # Generate carbon plots
    plot_carbon(carbon_df, combine, carb_dir)
    print(f"✅ Carbon analysis complete: {len(carbon_df)} entries")

    # Final summary
    print("\n" + "="*60)
    print("🎉 DEUTSCH-JOZSA EXPERIMENT COMPLETE - RESULTS SUMMARY")
    print("="*60)
    print(f"📁 Performance:     {perf_excel}")
    print(f"📁 Scalability:     {scal_excel}")
    print(f"📁 Reliability:     {rel_excel}")
    print(f"📁 Carbon:          {carb_excel}")
    print(f"🖥️  Device:          {get_device_name()}")
    print(f"📊 Total runs:      {len(perf_df)}")
    print(f"⚡ Total runtime:   {perf_df['runtime_s'].sum():.2f}s")
    print(f"🔬 Input sizes:     {sorted(perf_df['n'].unique())}")
    print(f"🎯 Success rate:    {perf_df['correct'].mean() * 100:.1f}%")

    print(f"\n📂 All results saved to:")
    for d in [perf_dir, scal_dir, rel_dir, carb_dir]:
        print(f"   • {d}")

    return perf_df

# ============================================================
# Main execution for Kaggle
# ============================================================
#This main block serves as the script entry point, 
#   performing GPU cleanup and launching the full Deutsch–Jozsa benchmark.
#It runs the experiment, prints a detailed summary of results, 
#        and reports performance metrics and success rates.
#It displays the generated output directory structure and 
#             confirms successful creation of all deliverables.

if __name__ == "__main__":
    # Clean up GPU state
    safe_gpu_cleanup()

    print("🚀 Starting Deutsch-Jozsa Quantum Benchmark on Kaggle")
    print("=" * 50)

    # Run the complete experiment
    results_df = run_dj_experiment()

    if results_df is not None:
        # Display final results summary
        print("\n📊 FINAL RESULTS SUMMARY")
        print("=" * 30)
        print(f"Total experiments: {len(results_df)}")
        print(f"Input sizes tested: {sorted(results_df['n'].unique())}")
        print(f"Average runtime: {results_df['runtime_s'].mean():.6f}s")
        print(f"Success rate: {results_df['correct'].mean() * 100:.1f}%")
        print(f"Device used: {get_device_name()}")

        # Show folder structure
        print("\n📁 GENERATED OUTPUT STRUCTURE:")
        base_dir = '/kaggle/working'
        for root, dirs, files in os.walk(base_dir):
            # Only show our output directories
            if any(x in root for x in ['Performance', 'Scalability', 'Reliability', 'Carbon footprints']):
                level = root.replace(base_dir, '').count(os.sep)
                indent = ' ' * 2 * level
                print(f'{indent}📁 {os.path.basename(root)}/')
                sub_indent = ' ' * 2 * (level + 1)
                for file in files:
                    if file.endswith(('.xlsx', '.png')):
                        file_path = os.path.join(root, file)
                        size = os.path.getsize(file_path) / 1024  # KB
                        icon = "📊" if file.endswith('.xlsx') else "🖼️"
                        print(f'{sub_indent}{icon} {file} ({size:.1f} KB)')

        print("\n✅ All Deutsch-Jozsa deliverables generated successfully!")
        print("   • Performance/performance_results.xlsx + perf_*.png")
        print("   • Scalability/scalability_results.xlsx + scal_*.png")
        print("   • Reliability/reliability_results.xlsx + rel_*.png")
        print("   • Carbon footprints/carbon_by_country/carbon_results.xlsx + carbon_*.png")
    else:
        print("❌ Deutsch-Jozsa benchmark failed - no results generated")

