#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# ----------------------------------------------------------------------------------------------------------------
# GPU-accelerated Empirical Evaluation: Quantum SVM on Iris (Noiseless) – Quantum Baseline
# ----------------------------------------------------------------------------------------------------------------

# Notes: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# Code focuses on Performance, Scalability, Reliability, Carbon footprints
# Output folders are:
    #   Performance = runtime
    #   Scalability = growth of runtime as N increases (digits/bits).
    #   Reliability = success rate + dispersion across repetitions.
    #   Carbon footprints = derived *only* from PERFORMANCE totals
    #   (sum of successful wall-times), device power 65 Watts fixed for comparasion, PUE 1.2 fixed, 
    #   country carbon intensity (kg CO2/kWh). I did not use scalability or reliability results for CO2.

#      Carbon Data File: 
#      Uses ONLY Performance runtimes (not Scalability/Reliability), 
#      Placed on my Desktop Excel of country intensities "Filtered CO2 intensity 236 Countries.xlsx"
#      (CSV or XLSX; year column optional. I have selected --year-select latest.)
# ----------------------------------------------------------------------------------------------------------------

"""11 SVM
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/i222070tabidahusmani/11-svm.367f2831-6859-49d7-bd12-f2ba7927af25.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20251117/auto/storage/goog4_request%26X-Goog-Date%3D20251117T183207Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D183bc599f0898f00a90185552829de8eaf2afcbd34820d4f20a128a56c5f79e2c38edf36b545841a06c2f620e77694b1f7bb327acad121a78e7cc262cfae3f09fd3ceb2db57ad0a1a66c61cf824b45991b28a64c072a7d21f297017818302e84e8d72e072e39f3a3747166f231aff359f9015af907facd80a4606cdf55f537a5094e9b0009de7b1e256678a73af8a9c826c032b09a1539132227985d79f99b7c75f9cf2a8f54fc4b4ff0ccde7ad0727bb174e4ab55b507b941058231bcbfa3767c8fea52bc12e9d476418b077f364ebc29b216337cd8b21c155db52abeef3077057bf23494ebaa5746bad6599b62c8f66b3777db6971a8ae51c84a92e673afcc
"""


#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# ------------********------------ Imports

import os, sys, time, tracemalloc, pathlib, warnings, math
from dataclasses import dataclass
from typing import List, Tuple, Dict, Any
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed

# ------------********------------
# GPU Setup and Dependencies
# ------------********------------

print("🔍 Checking GPU availability...")

HAS_GPU = False
cp = None

try:
    import cupy as cp
    # Test if GPU is available and working
    with cp.cuda.Device(0):
        # Simple test to verify GPU functionality
        test_array = cp.zeros(10, dtype=cp.float32)
        result = cp.sum(test_array)
        HAS_GPU = True
        print(f"✅ GPU detected: {cp.cuda.runtime.getDeviceProperties(0)['name'].decode()}")
        print(f"   Memory: {cp.cuda.Device().mem_info[1] / 1e9:.2f} GB")
        print(f"   Compute Capability: {cp.cuda.runtime.getDeviceProperties(0)['major']}.{cp.cuda.runtime.getDeviceProperties(0)['minor']}")
except ImportError:
    print("❌ CuPy not available, falling back to NumPy")
    import numpy as cp
except Exception as e:
    print(f"⚠️  GPU setup failed: {e}, falling back to NumPy")
    import numpy as cp

# If GPU failed, use NumPy

if not HAS_GPU:
    import numpy as cp
    print("🔄 Using NumPy (CPU) backend")

# Install required packages

def _ensure(pkgs: List[str]):
    import importlib, subprocess
    missing = []
    for p in pkgs:
        try:
            importlib.import_module(p)
        except ImportError:
            missing.append(p)
    if missing:
        print(f"[setup] Installing missing packages: {missing}")
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *missing])
        except Exception as e:
            print(f"[setup] Auto-install failed: {e}")

_ensure(["pandas", "matplotlib", "openpyxl", "psutil", "scikit-learn"])


# ------------********------------
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# sklearn imports

from sklearn import datasets
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler, label_binarize
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, hinge_loss
# ------------********------------


# GPU utility functions

def get_device_name() -> str:
    #Get current device name

    if HAS_GPU:
        try:
            return f"GPU: {cp.cuda.runtime.getDeviceProperties(0)['name'].decode()}"
        except:
            return "GPU: Unknown"
    return "CPU: NumPy"

def safe_gpu_cleanup():
    #Safely cleanup GPU memory

    if HAS_GPU:
        try:
            cp.get_default_memory_pool().free_all_blocks()
        except:
            pass

# Thread-safe GPU operations

_gpu_lock = threading.Lock()

def run_experiment_thread_safe(args):

   # """
   # Thread-safe GPU experiment runner.
   # Uses a lock to prevent multiple threads from accessing GPU simultaneously.
   # """

    n_components, seed = args

    with _gpu_lock:  # Ensure only one thread uses GPU at a time
        return _run_single_experiment(n_components, seed)

# ------------********------------
# ========================= Quantum SVM Core ======
# ------------********------------

I2 = np.eye(2, dtype=np.complex128)
H = (1/np.sqrt(2.0)) * np.array([[1,1],[1,-1]], dtype=np.complex128)

def Rz(theta: float):
    c = math.cos(theta/2.0); s = math.sin(theta/2.0)
    return np.array([[c-1j*s, 0],[0, c+1j*s]], dtype=np.complex128)

def Rx(theta: float):
    c = math.cos(theta/2.0); s = math.sin(theta/2.0)
    return np.array([[c, -1j*s],[-1j*s, c]], dtype=np.complex128)

def apply_1q(state: np.ndarray, U: np.ndarray, q: int, nqubits: int):

    """Apply 1-qubit U to qubit index q (0=leftmost) on |ψ⟩ (2^n vector)."""
    ops = [I2]*nqubits
    ops[q] = U
    bigU = ops[0]
    for k in range(1, nqubits):
        bigU = np.kron(bigU, ops[k])
    return bigU @ state

def apply_ZZ_phase(state: np.ndarray, i: int, j: int, theta: float, nqubits: int):

    """Apply exp(-i θ/2 Z_i Z_j) by phasing amplitudes in place (no big matrix)."""
    dim = state.shape[0]
    pos_i = (nqubits - 1 - i)  # bit positions from left
    pos_j = (nqubits - 1 - j)
    phase_pos = np.exp(-1j * theta/2.0)
    phase_neg = np.exp(+1j * theta/2.0)
    for idx in range(dim):
        bi = (idx >> pos_i) & 1
        bj = (idx >> pos_j) & 1
        zi = +1 if bi == 0 else -1
        zj = +1 if bj == 0 else -1
        state[idx] *= (phase_pos if (zi*zj) == +1 else phase_neg)

def feature_state_from_x(x: np.ndarray) -> np.ndarray:
    
    #Feature map |ψ(x)⟩, q=len(x):
    #  |0…0> → H on all qubits →
    #  For each i: RZ(π x_i), RX(π x_i) →
     # For i<j: ZZ(π x_i x_j).
    
    q = int(x.shape[0])
    dim = 1 << q
    state = np.zeros((dim,), dtype=np.complex128); state[0] = 1.0
    for i in range(q):
        state = apply_1q(state, H, i, q)
    for i in range(q):
        state = apply_1q(state, Rz(math.pi*float(x[i])), i, q)
        state = apply_1q(state, Rx(math.pi*float(x[i])), i, q)
    for i in range(q):
        for j in range(i+1, q):
            theta = math.pi * float(x[i]) * float(x[j])
            apply_ZZ_phase(state, i, j, theta, q)
    nrm = np.linalg.norm(state)
    return state if nrm == 0 else state / nrm

def fidelity_kernel_matrix(XA: np.ndarray, XB: np.ndarray) -> np.ndarray:

    """K[i,j] = |⟨ψ(xA_i)|ψ(xB_j)⟩|^2."""
    states_A = [feature_state_from_x(XA[i]) for i in range(XA.shape[0])]
    states_B = [feature_state_from_x(XB[i]) for i in range(XB.shape[0])]
    K = np.empty((XA.shape[0], XB.shape[0]), dtype=np.float64)
    for i, sa in enumerate(states_A):
        overlaps = np.array([np.vdot(sa, sb) for sb in states_B])
        K[i, :] = (np.abs(overlaps)**2).real
    return K

def safe_hinge_loss(y_true, df_scores, classes):
    
    # 1) Try sklearn.metrics.hinge_loss(y_true, decision_function, labels=classes).
   #   2) Fallback: manual OvR hinge loss: mean max(0, 1 - y_ic * f_ic), y_ic ∈ {-1,+1}.
   
    y_true = np.asarray(y_true)
    df_scores = np.asarray(df_scores)
    try:
        return float(hinge_loss(y_true, df_scores, labels=classes))
    except TypeError:
        pass
    if df_scores.ndim == 1:
        # Binary to 2D scores: [-s, +s]
        df_scores = df_scores.reshape(-1,1)
        df_scores = np.hstack([-df_scores, df_scores])
        classes = np.array(classes[:2])
    Y_bin = label_binarize(y_true, classes=classes)  # {0,1}
    Y = 2.0*Y_bin - 1.0                              # {-1,+1}
    loss = np.maximum(0.0, 1.0 - Y*df_scores)
    return float(np.mean(loss))

def _run_single_experiment(n_components: int, seed: int) -> dict:
   
   # Core experiment logic - run single Quantum SVM experiment.
    # Fixed parameters matching my command line requirements

    max_iter = 1000
    Cval = 1.0
    test_size = 0.3
    acc_tol = 0.90

    n_comp_eff = int(max(1, min(4, int(n_components))))  # clamp to [1..4]

    iris = datasets.load_iris()
    X_all = iris.data.astype(np.float64)
    y_all = iris.target.astype(np.int32)

    X_train, X_test, y_train, y_test = train_test_split(
        X_all, y_all, test_size=test_size, random_state=seed, stratify=y_all
    )

    # Standardize → PCA to n_comp_eff

    scaler = StandardScaler()
    Xtr = scaler.fit_transform(X_train)
    pca = PCA(n_components=n_comp_eff, random_state=seed)
    Xtr = pca.fit_transform(Xtr)
    Xte = pca.transform(scaler.transform(X_test))

    # Map each feature to [0,1] (fit on train only) for angles

    xmin = Xtr.min(axis=0)
    xmax = Xtr.max(axis=0)
    span = np.maximum(xmax - xmin, 1e-9)
    Xtr_q = np.clip((Xtr - xmin) / span, 0.0, 1.0)
    Xte_q = np.clip((Xte - xmin) / span, 0.0, 1.0)

    tracemalloc.start()
    t0 = time.perf_counter()

    # Quantum fidelity kernel (train & test Gram matrices)

    K_train = fidelity_kernel_matrix(Xtr_q, Xtr_q)
    K_test  = fidelity_kernel_matrix(Xte_q, Xtr_q)

    # Train SVM with precomputed kernel

    clf = SVC(kernel="precomputed", C=float(Cval), max_iter=int(max_iter), decision_function_shape="ovr")
    clf.fit(K_train, y_train)
    y_pred = clf.predict(K_test)

    # Metrics
    acc = accuracy_score(y_test, y_pred)
    df_scores = clf.decision_function(K_test)
    hloss = safe_hinge_loss(y_test, df_scores, clf.classes_)

    runtime = time.perf_counter() - t0
    _, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    # Cleanup GPU memory
    safe_gpu_cleanup()

    return {
        "n": int(n_components),
        "pca_components_eff": int(n_comp_eff),
        "kernel": "quantum_fidelity",
        "C": float(Cval),
        "max_iter": int(max_iter),
        "test_size": float(test_size),
        "seed": int(seed),
        "accuracy": float(acc),
        "hinge_loss": float(hloss),
        "correct": bool(acc >= acc_tol),
        "runtime_s": float(runtime),
        "peak_mem_mb": float(peak / (1024**2)),
        "n_train": int(X_train.shape[0]),
        "n_test": int(X_test.shape[0]),
        "device": get_device_name()
    }
# ------------********------------
# ============================== Carbon I/O 
# ------------********------------

#def resolve_excel_path resolves a user-provided Excel filename to an existing absolute path, 
#checking both the given path and a Desktop fallback.



def resolve_excel_path(excel_arg: str) -> str:
    p = pathlib.Path(excel_arg)
    if p.is_absolute() and p.exists():
        return str(p)
    desktop = pathlib.Path.home() / "Desktop" / excel_arg
    return str(desktop if desktop.exists() else p)

#def load_carbon_excel loads and cleans a carbon-intensity dataset by 
# inferring country/year/intensity columns, fixing units, and optionally selecting the latest year.


def load_carbon_excel(path: str, year_select: str = "latest") -> pd.DataFrame:
    df = pd.read_excel(path)
    cols = {c.lower(): c for c in df.columns}
    cand_country = next((v for k, v in cols.items() if "country" in k or "nation" in k or k == "location"), None)
    if cand_country is None:
        raise ValueError("No 'Country' column found.")
    cand_year = next((v for k, v in cols.items() if "year" in k or "date" in k), None)
    cand_intensity = next((v for k, v in cols.items()
                           if "intensity" in k or ("co2" in k and "kwh" in k) or "kgco2" in k or "gco2" in k), None)
    if cand_intensity is None:
        numeric_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
        if cand_year in numeric_cols:
            numeric_cols.remove(cand_year)
        if not numeric_cols:
            raise ValueError("No numeric intensity column detected.")
        cand_intensity = numeric_cols[0]
    keep = [cand_country] + ([cand_year] if cand_year else []) + [cand_intensity]
    df = df[keep].copy()
    df.columns = ["Country", "Year", "Intensity"] if len(keep) == 3 else ["Country", "Intensity"]
    if "Year" in df.columns and year_select.lower() == "latest":
        df = df.sort_values(["Country", "Year"]).groupby("Country", as_index=False).tail(1)

    # Heuristic unit fix: if median looks like g/kWh, convert to kg/kWh
    med = float(df["Intensity"].dropna().median())
    if med > 50:
        df["Intensity"] = df["Intensity"] / 1000.0

    return df.dropna(subset=["Country", "Intensity"]).reset_index(drop=True)

#def compute_carbon converts total experiment runtime into energy use and per-country CO₂ emissions, 
#returning detailed country-wise results and a summary table.
def compute_carbon(perf_df: pd.DataFrame, intensity_df: pd.DataFrame,
                   power_watts: float, pue: float, combine: bool) -> tuple[pd.DataFrame, pd.DataFrame]:
    total_runtime_s = float(perf_df["runtime_s"].sum())
    kWh_total = power_watts * pue * total_runtime_s / 3_600_000.0
    df = intensity_df.copy()
    df["kWh"] = kWh_total
    df["kgCO2e"] = df["Intensity"] * df["kWh"]


    carbon_output = df.sort_values("kgCO2e", ascending=False)

    summary = pd.DataFrame({
        "total_runtime_s": [total_runtime_s],
        "power_watts": [power_watts],
        "PUE": [pue],
        "kWh_total": [kWh_total],
        "median_intensity_kg_per_kWh": [float(df["Intensity"].median())],
        "mean_kgCO2e_across_countries": [float(df["kgCO2e"].mean())],
        "device": [perf_df["device"].iloc[0] if "device" in perf_df.columns else "Unknown"],
        "combine_mode": [combine],
        "countries_analyzed": [len(df)]
    })
    return carbon_output, summary

# ------------********------------
# ============================== Plot Helpers
# ------------********------------

plt_kwargs = dict(dpi=140, bbox_inches="tight")

def _boxplot_with_labels(data, labels):
    # Matplotlib 3.9 renamed 'labels' -> 'tick_labels'
    try:
        plt.boxplot(data, tick_labels=labels)
    except TypeError:
        plt.boxplot(data, labels=labels)

# ------------********------------
#def plot_performance aggregates experiment results by PCA component count and visualizes mean runtime scaling.
#It generates a runtime vs PCA-components plot annotated with the active compute device and saves it to disk.
#The function also plots mean classification accuracy versus PCA components, providing a performance–accuracy tradeoff view.

def plot_performance(df: pd.DataFrame, outdir: str):
    g = df.groupby("n")["runtime_s"].mean().reset_index()
    plt.figure()
    plt.plot(g["n"], g["runtime_s"], marker="o", linewidth=2, markersize=8)
    plt.title(f"Performance: Runtime vs PCA Components\n{get_device_name()}")
    plt.xlabel("PCA Components (Qubits)")
    plt.ylabel("Runtime (s)")
    plt.grid(True)
    plt.savefig(os.path.join(outdir, "perf_runtime_vs_n.png"), **plt_kwargs)
    plt.close()

    g2 = df.groupby("n")["accuracy"].mean().reset_index()
    plt.figure()
    plt.plot(g2["n"], g2["accuracy"], marker="s", linewidth=2, markersize=8)
    plt.title(f"Performance: Mean Accuracy vs PCA Components\n{get_device_name()}")
    plt.xlabel("PCA Components (Qubits)")
    plt.ylabel("Accuracy")
    plt.grid(True)
    plt.savefig(os.path.join(outdir, "perf_accuracy_vs_n.png"), **plt_kwargs)
    plt.close()

# ------------********------------
def plot_scalability(df: pd.DataFrame, outdir: str):
    g = df.groupby("n")["peak_mem_mb"].mean().reset_index()
    plt.figure()
    plt.plot(g["n"], g["peak_mem_mb"], marker="^", linewidth=2, markersize=8, color='green')
    plt.title(f"Scalability: Memory vs PCA Components\n{get_device_name()}")
    plt.xlabel("PCA Components (Qubits)")
    plt.ylabel("Memory (MB)")
    plt.grid(True)
    plt.savefig(os.path.join(outdir, "scal_memory_vs_n.png"), **plt_kwargs)
    plt.close()

    g2 = df.groupby("n")["runtime_s"].mean().reset_index()
    plt.figure()
    plt.loglog(g2["n"], g2["runtime_s"], marker="o", linewidth=2, markersize=8)
    plt.title(f"Scalability: Runtime (log-log)\n{get_device_name()}")
    plt.xlabel("PCA Components")
    plt.ylabel("Runtime (s)")
    plt.grid(True, which="both")
    plt.savefig(os.path.join(outdir, "scal_loglog_runtime.png"), **plt_kwargs)
    plt.close()

# ------------********------------
def plot_reliability(df: pd.DataFrame, outdir: str):
    data = [df[df["n"] == n]["accuracy"].values for n in sorted(df["n"].unique())]
    plt.figure()
    _boxplot_with_labels(data, labels=sorted(df["n"].unique()))
    plt.title(f"Reliability: Accuracy Distribution by PCA Components\n{get_device_name()}")
    plt.xlabel("PCA Components (Qubits)")
    plt.ylabel("Accuracy")
    plt.grid(True)
    plt.savefig(os.path.join(outdir, "rel_accuracy_boxplot.png"), **plt_kwargs)
    plt.close()

    g = df.groupby("n")["correct"].mean().reset_index()
    plt.figure()
    plt.plot(g["n"], g["correct"], marker="o", linewidth=2, markersize=8)
    plt.title(f"Reliability: Success Rate vs PCA Components\n{get_device_name()}")
    plt.xlabel("PCA Components")
    plt.ylabel("Success Rate")
    plt.grid(True)
    plt.savefig(os.path.join(outdir, "rel_success_vs_n.png"), **plt_kwargs)
    plt.close()

# ------------********------------
def plot_carbon(df: pd.DataFrame, combine: bool, outdir: str):
    """Generate carbon footprint plots - ALWAYS country-wise"""
    # Top 15 highest emissions
    top = df.nlargest(15, "kgCO2e")
    plt.figure(figsize=(12, 8))
    plt.barh(top["Country"][::-1], top["kgCO2e"][::-1], color='red', alpha=0.7)
    plt.xlabel("kg CO2e (higher = dirtier grid)", fontsize=12)
    plt.title(f"Carbon: Top 15 Highest Emissions\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(outdir, "carbon_top15.png"), **plt_kwargs)
    plt.close()

    # Bottom 15 lowest emissions
    bot = df.nsmallest(15, "kgCO2e")
    plt.figure(figsize=(12, 8))
    plt.barh(bot["Country"][::-1], bot["kgCO2e"][::-1], color='green', alpha=0.7)
    plt.xlabel("kg CO2e (lower = cleaner grid)", fontsize=12)
    plt.title(f"Carbon: Bottom 15 Lowest Emissions\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(outdir, "carbon_bottom15.png"), **plt_kwargs)
    plt.close()

    # Distribution histogram
    plt.figure(figsize=(10, 6))
    plt.hist(df["kgCO2e"], bins=30, alpha=0.7, edgecolor='black', color='orange')
    plt.xlabel("kg CO2e for this experiment", fontsize=12)
    plt.ylabel("Frequency", fontsize=12)
    plt.title(f"Carbon: Emission Distribution\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "carbon_distribution.png"), **plt_kwargs)
    plt.close()

    # CDF plot
    xs = np.sort(df["kgCO2e"].values)
    ys = np.arange(1, len(xs) + 1) / len(xs)
    plt.figure(figsize=(10, 6))
    plt.plot(xs, ys, linewidth=2, color='purple')
    plt.xlabel("kg CO2e", fontsize=12)
    plt.ylabel("CDF", fontsize=12)
    plt.title(f"Carbon: Cumulative Distribution\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "carbon_cdf.png"), **plt_kwargs)
    plt.close()

# ------------********------------
# ============================== Utility Functions ==============================
# ------------********------------

def ensure_dir(d: str):
    """Ensure directory exists"""
    os.makedirs(d, exist_ok=True)

def to_excel(dfs: Dict[str, pd.DataFrame], path: str):
    """Save multiple DataFrames to Excel with different sheets"""
    with pd.ExcelWriter(path, engine="openpyxl") as w:
        for name, df in dfs.items():
            df.to_excel(w, index=False, sheet_name=name[:31])

# ------------********------------
# ============================== Main Experiment Runner ==============================
# ------------********------------

def run_quantum_svm_experiment():
    """
    Main Quantum SVM experiment runner with hardcoded parameters for Kaggle.
    Equivalent to: --sizes 1 2 3 4 --steps 1000 --trials 10 --kernel quantum
                   --C 1.0 --test-size 0.3 --acc-tol 0.95
                   --device-power-watts 65 --pue 1.2 --combine
    """
    # Experiment parameters
    sizes = [1, 2, 3, 4]  # PCA components (qubits)
    trials = 10   # trials per size
    max_iter = 1000
    Cval = 1.0
    test_size = 0.3
    acc_tol = 0.90
    method = "quantum_svm"
    workers = 4   # Number of parallel threads

    # Carbon parameters
    device_power_watts = 65.0
    pue = 1.2
    combine = True

    print(f"🚀 Starting Quantum SVM experiments on {get_device_name()}")
    print(f"🔧 Configuration:")
    print(f"   PCA Components (Qubits): {sizes}")
    print(f"   SVM max iterations: {max_iter}")
    print(f"   Trials per size: {trials}")
    print(f"   Regularization C: {Cval}")
    print(f"   Test size: {test_size}")
    print(f"   Accuracy tolerance: {acc_tol}")
    print(f"   Method: {method}")
    print(f"   Workers: {workers}")
    print(f"   Device power: {device_power_watts}W")
    print(f"   PUE: {pue}")
    print(f"   Combine carbon: {combine}")

    # Create output folders
    perf_dir = os.path.join(os.getcwd(), "Performance")
    scal_dir = os.path.join(os.getcwd(), "Scalability")
    rel_dir  = os.path.join(os.getcwd(), "Reliability")
    carb_root = os.path.join(os.getcwd(), "Carbon footprints")
    carb_dir  = os.path.join(carb_root, "carbon_by_country")

    for d in [perf_dir, scal_dir, rel_dir, carb_dir]:
        ensure_dir(d)

    # Prepare jobs
    jobs = []
    for n in sizes:
        for i in range(trials):
            jobs.append((n, 1000 + 17 * n + i))

    all_rows = []

    def _consume(row):
        """Process completed job results"""
        all_rows.append(row)
        print(f"  ✅ PCA={row['n']}, seed={row['seed']} (runtime={row['runtime_s']:.6f}s, accuracy={row['accuracy']:.3f}, correct={row['correct']})")

    # Execute jobs with thread-based parallelization
    print(f"🔀 Running {len(jobs)} jobs in parallel with {workers} threads...")

    if workers > 1 and len(jobs) > 1:
        with ThreadPoolExecutor(max_workers=workers) as executor:
            # Submit all jobs
            future_to_job = {executor.submit(run_experiment_thread_safe, job): job for job in jobs}

            # Collect results as they complete
            for future in as_completed(future_to_job):
                try:
                    result = future.result()
                    _consume(result)
                except Exception as e:
                    job = future_to_job[future]
                    print(f"❌ Job failed PCA={job[0]}, seed={job[1]}: {e}")
    else:
        # Fallback to sequential execution
        for job in jobs:
            result = run_experiment_thread_safe(job)
            _consume(result)

    # Check if we have any successful results
    if not all_rows:
        print("❌ All jobs failed! Running sequentially as fallback...")
        for job in jobs:
            try:
                result = _run_single_experiment(job[0], job[1])
                _consume(result)
            except Exception as e:
                print(f"❌ Sequential fallback also failed for PCA={job[0]}, seed={job[1]}: {e}")

    if not all_rows:
        print("💥 CRITICAL: No experiments completed successfully!")
        return None

    perf_df = pd.DataFrame(all_rows)

# ------------********------------
    # ---------------- Performance Results ----------------

    print("📊 Generating Performance results...")
    perf_excel = os.path.join(perf_dir, "performance_results.xlsx")
    perf_agg = perf_df.groupby("n").agg({
        "runtime_s": "mean",
        "accuracy": "mean",
        "peak_mem_mb": "mean",
        "hinge_loss": "mean",
        "correct": "mean"
    }).reset_index()

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "raw_runs": perf_df,
            "aggregated": perf_agg
        }, perf_excel)

    plot_performance(perf_df, perf_dir)

# ------------********------------
    # ---------------- Scalability Results ----------------

    print("📈 Generating Scalability results...")
    scal_excel = os.path.join(scal_dir, "scalability_results.xlsx")
    scal_agg = perf_df.groupby("n").agg({
        "runtime_s": "mean",
        "peak_mem_mb": "mean",
        "accuracy": "mean"
    }).reset_index()

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "from_perf_runs": perf_df[["n", "seed", "runtime_s", "peak_mem_mb", "accuracy", "hinge_loss"]],
            "aggregated": scal_agg
        }, scal_excel)

    plot_scalability(perf_df, scal_dir)

# ------------********------------
    # ---------------- Reliability Results ----------------

    print("🎯 Generating Reliability results...")
    rel_excel = os.path.join(rel_dir, "reliability_results.xlsx")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "correctness_analysis": perf_df[["n", "seed", "accuracy", "hinge_loss", "correct"]]
        }, rel_excel)

    plot_reliability(perf_df, rel_dir)

# ------------********------------
    # ---------------- Carbon Footprint Results ----------------

    print("🌍 Generating Carbon footprint results...")

    # Load carbon data from Kaggle input directory
    excel_path = "/kaggle/input/masters/Filtered CO2 intensity 236 Countries.xlsx"
    intensity_df = None

    try:
        # Try to load from the exact path
        intensity_df = pd.read_excel(excel_path)
        print(f"✅ Loaded carbon data from: {excel_path}")
        print(f"   Columns found: {list(intensity_df.columns)}")
        print(f"   Countries loaded: {len(intensity_df)}")

        # Auto-detect and process columns
        cols = {c.lower(): c for c in intensity_df.columns}
        cand_country = next((v for k,v in cols.items() if "country" in k or "nation" in k or k=="location"), None)
        if cand_country is None:
            raise ValueError("No 'Country' column found.")

        cand_intensity = next((v for k,v in cols.items() if "intensity" in k or ("co2" in k and ("kwh" in k or "/kwh" in k)) or "kgco2" in k or "gco2" in k), None)

        if cand_intensity is None:
            numeric_cols = [c for c in intensity_df.columns if pd.api.types.is_numeric_dtype(intensity_df[c])]
            if not numeric_cols:
                raise ValueError("No numeric intensity column detected.")
            cand_intensity = numeric_cols[0]

        # Keep only necessary columns
        intensity_df = intensity_df[[cand_country, cand_intensity]].copy()
        intensity_df.columns = ["Country", "Intensity"]

        # Convert gCO2/kWh to kgCO2/kWh if needed
        med = float(intensity_df["Intensity"].dropna().median())
        if med > 50:
            intensity_df["Intensity"] = intensity_df["Intensity"] / 1000.0

        intensity_df = intensity_df.dropna(subset=["Country", "Intensity"]).reset_index(drop=True)
        print(f"✅ Processed carbon data for {len(intensity_df)} countries")

    except Exception as e:
        print(f"❌ ERROR loading carbon data: {e}")
        print("💡 Using sample carbon data as fallback...")
        # Create sample data similar to other codes
        countries = ["France", "Sweden", "Norway", "Switzerland", "Austria", "Germany", "United States", "China", "India"]
        intensities = [52, 41, 32, 45, 62, 385, 389, 537, 708]
        intensity_df = pd.DataFrame({
            "Country": countries,
            "Intensity": [i/1000.0 for i in intensities]  # Convert to kg/kWh
        })

    ensure_dir(carb_dir)
    carbon_df, summary_df = compute_carbon(perf_df, intensity_df,
                                           power_watts=device_power_watts,
                                           pue=pue, combine=combine)
    carb_excel = os.path.join(carb_dir, "carbon_results.xlsx")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "carbon_results": carbon_df,
            "summary": summary_df,
            "intensity_input": intensity_df,
            "performance_reference": perf_df[["n", "seed", "runtime_s"]]
        }, carb_excel)

    # Generate carbon plots
    plot_carbon(carbon_df, combine, carb_dir)
    print(f"✅ Carbon analysis complete: {len(carbon_df)} entries")

    # Final summary
    print("\n" + "="*60)
    print("🎉 QUANTUM SVM EXPERIMENT COMPLETE - RESULTS SUMMARY")
    print("="*60)
    print(f"📁 Performance:     {perf_excel}")
    print(f"📁 Scalability:     {scal_excel}")
    print(f"📁 Reliability:     {rel_excel}")
    print(f"📁 Carbon:          {carb_excel}")
    print(f"🖥️  Device:          {get_device_name()}")
    print(f"📊 Total runs:      {len(perf_df)}")
    print(f"⚡ Total runtime:   {perf_df['runtime_s'].sum():.2f}s")
    print(f"🔬 PCA Components:  {sorted(perf_df['n'].unique())}")
    print(f"🎯 Success rate:    {perf_df['correct'].mean() * 100:.1f}%")
    print(f"📏 Mean accuracy:   {perf_df['accuracy'].mean():.3f}")
    print(f"📐 Mean hinge loss: {perf_df['hinge_loss'].mean():.3f}")

    print(f"\n📂 All results saved to:")
    for d in [perf_dir, scal_dir, rel_dir, carb_dir]:
        print(f"   • {d}")

    return perf_df

# ------------********------------
# Main execution for Kaggle
# ------------********-------------
if __name__ == "__main__":
    # Clean up GPU state
    safe_gpu_cleanup()

    print("🚀 Starting Quantum SVM Benchmark on Kaggle")
    print("=" * 50)

    # Run the complete experiment
    results_df = run_quantum_svm_experiment()

    if results_df is not None:
        # Display final results summary
        print("\n📊 FINAL RESULTS SUMMARY")
        print("=" * 30)
        print(f"Total experiments: {len(results_df)}")
        print(f"PCA Components tested: {sorted(results_df['n'].unique())}")
        print(f"Average runtime: {results_df['runtime_s'].mean():.6f}s")
        print(f"Success rate: {results_df['correct'].mean() * 100:.1f}%")
        print(f"Average accuracy: {results_df['accuracy'].mean():.3f}")
        print(f"Average hinge loss: {results_df['hinge_loss'].mean():.3f}")
        print(f"Device used: {get_device_name()}")

        # Show folder structure
        print("\n📁 GENERATED OUTPUT STRUCTURE:")
        base_dir = '/kaggle/working'
        for root, dirs, files in os.walk(base_dir):
            # Only show our output directories
            if any(x in root for x in ['Performance', 'Scalability', 'Reliability', 'Carbon footprints']):
                level = root.replace(base_dir, '').count(os.sep)
                indent = ' ' * 2 * level
                print(f'{indent}📁 {os.path.basename(root)}/')
                sub_indent = ' ' * 2 * (level + 1)
                for file in files:
                    if file.endswith(('.xlsx', '.png')):
                        file_path = os.path.join(root, file)
                        size = os.path.getsize(file_path) / 1024  # KB
                        icon = "📊" if file.endswith('.xlsx') else "🖼️"
                        print(f'{sub_indent}{icon} {file} ({size:.1f} KB)')

        print("\n✅ All Quantum SVM deliverables generated successfully!")
        print("   • Performance/performance_results.xlsx + perf_*.png")
        print("   • Scalability/scalability_results.xlsx + scal_*.png")
        print("   • Reliability/reliability_results.xlsx + rel_*.png")
        print("   • Carbon footprints/carbon_by_country/carbon_results.xlsx + carbon_*.png")
    else:
        print("❌ Quantum SVM benchmark failed - no results generated")

