#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------------------------------------------------
# GPU-accelerated Quantum Grover Search (Ideal/Noiseless) — Benchmarks
# ----------------------------------------------------------------------------------------------------------------

# Notes: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# Code focuses on Performance, Scalability, Reliability, Carbon footprints
# Output folders are:
    #   Performance = runtime
    #   Scalability = growth of runtime as N increases (digits/bits).
    #   Reliability = success rate + dispersion across repetitions.
    #   Carbon footprints = derived *only* from PERFORMANCE totals
    #   (sum of successful wall-times), device power 65 Watts fixed for comparasion, PUE 1.2 fixed, 
    #   country carbon intensity (kg CO2/kWh). I did not use scalability or reliability results for CO2.

#      Carbon Data File: 
#      Uses ONLY Performance runtimes (not Scalability/Reliability), 
#      Placed on my Desktop Excel of country intensities "Filtered CO2 intensity 236 Countries.xlsx"
#      (CSV or XLSX; year column optional. I have selected --year-select latest.)
# ----------------------------------------------------------------------------------------------------------------

"""1 Grover Algorithm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/i222070tabidahusmani/1-grover-algorithm.87daa35b-e2d9-4e85-a3ac-6dd65d68dae7.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20251204/auto/storage/goog4_request%26X-Goog-Date%3D20251204T174257Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D4219884083411481bf93dd0b385364832f1a36328065d868201122d804ae7413e4affd48456a3bb32d83063d9d12399d96b008565c49e2a41a25f36d32414748cd90c983b4061c9fca73bc7303bfac9de90863e200e62818a33f716552eb130deb4f7b59c88b914e2da6154e8090ac3991e7ff1b3cc4b16eb3857907d93c887ab025d35d808c77919e8e2fb4b4e19124f54d5772b8ac7968e9b2ae877ae6ee602af47b0885d2d03bdc6a8308484db3d9b5156adcdcca99ae2775749467c242391baf8177bf8ceb99d5d4a695cfa07bc24deea6b9688b6112dded4ac23d36cd04cfc5169a39b640bb1f833d9dbb0d07ad3a22fda7e15a1a55853ffc30c6500ea3
"""

# ------------********------------ Imports

import os, sys, time, tracemalloc, pathlib, warnings, math
from dataclasses import dataclass
from typing import List, Tuple, Dict, Any
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed

# ============================================================
# ------------********------------  GPU Setup and Dependencies
# ============================================================
print("🔍 Checking GPU availability for Quantum Grover...")

HAS_GPU = False
cp = None

try:
    import cupy as cp
    # Test if GPU is available and working
    with cp.cuda.Device(0):
        test_array = cp.zeros(10, dtype=cp.float32)
        result = cp.sum(test_array)
        HAS_GPU = True
        print(f"✅ GPU detected: {cp.cuda.runtime.getDeviceProperties(0)['name'].decode()}")
        print(f"   Memory: {cp.cuda.Device().mem_info[1] / 1e9:.2f} GB")
        print(f"   Compute Capability: {cp.cuda.runtime.getDeviceProperties(0)['major']}.{cp.cuda.runtime.getDeviceProperties(0)['minor']}")
except ImportError:
    print("❌ CuPy not available, falling back to NumPy")
    import numpy as cp
except Exception as e:
    print(f"⚠️  GPU setup failed: {e}, falling back to NumPy")
    import numpy as cp

# If GPU failed, use NumPy
if not HAS_GPU:
    import numpy as cp
    print("🔄 Using NumPy (CPU) backend")

# Install required packages
def _ensure(pkgs: List[str]):
    import importlib, subprocess
    missing = []
    for p in pkgs:
        try:
            importlib.import_module(p)
        except ImportError:
            missing.append(p)
    if missing:
        print(f"[setup] Installing missing packages: {missing}")
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *missing])
        except Exception as e:
            print(f"[setup] Auto-install failed: {e}")

_ensure(["pandas", "matplotlib", "openpyxl", "psutil"])

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# GPU utility functions
def get_device_name() -> str:
    #Get current device name
    if HAS_GPU:
        try:
            return f"GPU: {cp.cuda.runtime.getDeviceProperties(0)['name'].decode()}"
        except:
            return "GPU: Unknown"
    return "CPU: NumPy"

def safe_gpu_cleanup():
    # Safely cleanup GPU memory"
    if HAS_GPU:
        try:
            cp.get_default_memory_pool().free_all_blocks()
        except:
            pass

# Thread-safe GPU operations
_gpu_lock = threading.Lock()

def run_grover_experiment_thread_safe(args):
    
    # Thread-safe GPU Grover experiment runner.
    # Uses a lock to prevent multiple threads from accessing GPU simultaneously.
    
    N, marked_count, seed, shots, acc_tol = args
    with _gpu_lock:
        return _run_single_grover_experiment(N, marked_count, seed, shots, acc_tol)

# ------------********------------
# ========================= Quantum Grover Simulation Core =========================
# ------------********------------ 
def grover_iterations(N: int, marked_count: int) -> Tuple[int, float, float]:
    
    # Compute Grover iteration count and theoretical success probability.
    # sin^2 θ = K/N, where K = marked_count.
    # Optimal iteration count: R* ≈ π/(4θ) - 0.5
    # Returns: R (int), p_success_theory, R_star (float)
    
    K = max(1, min(marked_count, N))
    sin2_theta = K / float(N)
    sin2_theta = min(max(sin2_theta, 0.0), 1.0)

    if sin2_theta <= 0.0:
        return 0, 0.0, 0.0

    theta = math.asin(math.sqrt(sin2_theta))
    R_star = math.pi / (4.0 * theta) - 0.5
    R = max(1, int(round(R_star)))
    p_theory = math.sin((2 * R + 1) * theta) ** 2
    p_theory = min(max(p_theory, 0.0), 1.0)

    return R, p_theory, R_star

def _apply_grover_iteration(state: cp.ndarray, marked_set: set, N: int) -> cp.ndarray:
    
    #Apply one Grover iteration: Oracle + Diffusion.
    #Oracle: phase-flip marked states
    #Diffusion: reflection about mean amplitude
    
    # Oracle: flip marked states
    for idx in marked_set:
        state[int(idx)] *= -1.0

    # Diffusion: D = 2|s⟩⟨s| - I
    mean_amp = cp.mean(state)
    state = 2.0 * mean_amp - state

    # Normalize
    norm = cp.linalg.norm(state)
    if norm > 0:
        state /= norm

    return state

def _run_single_grover_experiment(N: int, marked_count: int, seed: int,
                                 shots: int, acc_tol: float) -> dict:
    """
    Core experiment logic - run single Grover search benchmark.
    """
    # Use numpy RNG for consistency
    rng_np = np.random.default_rng(seed)

    K = max(1, min(marked_count, N))

    # Choose marked indices
    marked = rng_np.choice(N, size=K, replace=False)
    marked_set = set(int(i) for i in marked)

    # Grover parameters
    R, p_theory, R_star = grover_iterations(N, K)

    tracemalloc.start()
    t0 = time.perf_counter()

    # Initialize uniform superposition on GPU
    if HAS_GPU:
        state = cp.ones(N, dtype=cp.complex128) / math.sqrt(N)
    else:
        state = cp.ones(N, dtype=np.complex128) / math.sqrt(N)

    # Apply Grover iterations
    for _ in range(R):
        # Apply oracle and diffusion
        state = _apply_grover_iteration(state, marked_set, N)

    runtime = time.perf_counter() - t0
    _, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    # Success probability from statevector
    if HAS_GPU:
        probs = cp.abs(state) ** 2
        # Convert marked indices to GPU array
        marked_gpu = cp.array(list(marked_set), dtype=cp.int64)
        p_sim = float(cp.sum(probs[marked_gpu]))
    else:
        probs = np.abs(state) ** 2
        p_sim = float(np.sum(probs[list(marked_set)]))

    p_sim = min(max(p_sim, 0.0), 1.0)

    # Optional measurement sampling
    if shots and shots > 0:
        if HAS_GPU:
            # Sample from probabilities on GPU
            samples = cp.random.choice(N, size=shots, p=probs)
            marked_array = cp.array(list(marked_set))
            k_succ = cp.sum(cp.isin(samples, marked_array))
            p_meas = float(k_succ) / float(shots)
        else:
            samples = np.random.choice(N, size=shots, p=probs)
            k_succ = np.sum(np.isin(samples, list(marked_set)))
            p_meas = float(k_succ) / float(shots)
    else:
        p_meas = float("nan")

    # Metrics
    p_error_sim = float(p_sim - p_theory)
    p_error_meas = float(p_meas - p_theory) if not math.isnan(p_meas) else float("nan")
    success = bool(p_sim >= acc_tol)

    # Operations count
    # Each Grover iteration: 1 oracle query + 1 diffusion operation
    queries = R
    work_units = R * 2  # Oracle + Diffusion per iteration

    # Cleanup GPU memory
    safe_gpu_cleanup()

    return {
        "N": int(N),
        "n_bits": int(round(math.log2(N))) if N > 0 else 0,
        "marked_count": int(K),
        "seed": int(seed),
        "shots": int(shots),
        "runtime_s": float(runtime),
        "peak_mem_mb": float(peak / (1024**2)),
        "iterations": int(R),
        "queries": int(queries),
        "queries_theory": float(R_star),
        "p_success_theory": float(p_theory),
        "p_success_sim": float(p_sim),
        "p_success_meas": float(p_meas),
        "p_error_sim": p_error_sim,
        "p_error_meas": p_error_meas,
        "work_units": int(work_units),
        "accuracy_mean": float(p_sim),  # For consistency with Hamiltonian code
        "success": int(success),
        "device": get_device_name()
    }
# ------------********------------ 
# ============================== Carbon I/O 
# ------------********------------ 
#def resolve_excel_path

def resolve_excel_path(excel_arg: str) -> str:
    p = pathlib.Path(excel_arg)
    if p.is_absolute() and p.exists():
        return str(p)
    desktop = pathlib.Path.home() / "Desktop" / excel_arg
    return str(desktop if desktop.exists() else p)

def load_carbon_excel(path: str, year_select: str = "latest") -> pd.DataFrame:
    df = pd.read_excel(path)
    cols = {c.lower(): c for c in df.columns}
    cand_country = next((v for k, v in cols.items() if "country" in k or "nation" in k or k == "location"), None)
    if cand_country is None:
        raise ValueError("No 'Country' column found.")
    cand_year = next((v for k, v in cols.items() if "year" in k or "date" in k), None)
    cand_intensity = next((v for k, v in cols.items()
                           if "intensity" in k or ("co2" in k and "kwh" in k) or "kgco2" in k or "gco2" in k), None)
    if cand_intensity is None:
        numeric_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
        if cand_year in numeric_cols:
            numeric_cols.remove(cand_year)
        if not numeric_cols:
            raise ValueError("No numeric intensity column detected.")
        cand_intensity = numeric_cols[0]
    keep = [cand_country] + ([cand_year] if cand_year else []) + [cand_intensity]
    df = df[keep].copy()
    df.columns = ["Country", "Year", "Intensity"] if len(keep) == 3 else ["Country", "Intensity"]
    if "Year" in df.columns and year_select.lower() == "latest":
        df = df.sort_values(["Country", "Year"]).groupby("Country", as_index=False).tail(1)

    # Heuristic unit fix: if median looks like g/kWh, convert to kg/kWh
    med = float(df["Intensity"].dropna().median())
    if med > 50:
        df["Intensity"] = df["Intensity"] / 1000.0

    return df.dropna(subset=["Country", "Intensity"]).reset_index(drop=True)

def compute_carbon(perf_df: pd.DataFrame, intensity_df: pd.DataFrame,
                   power_watts: float, pue: float, combine: bool) -> tuple[pd.DataFrame, pd.DataFrame]:
    total_runtime_s = float(perf_df["runtime_s"].sum())
    kWh_total = power_watts * pue * total_runtime_s / 3_600_000.0
    df = intensity_df.copy()
    df["kWh"] = kWh_total
    df["kgCO2e"] = df["Intensity"] * df["kWh"]

    # ALWAYS return country-wise results (ignore combine parameter)
    carbon_output = df.sort_values("kgCO2e", ascending=False)

    summary = pd.DataFrame({
        "total_runtime_s": [total_runtime_s],
        "power_watts": [power_watts],
        "PUE": [pue],
        "kWh_total": [kWh_total],
        "median_intensity_kg_per_kWh": [float(df["Intensity"].median())],
        "mean_kgCO2e_across_countries": [float(df["kgCO2e"].mean())],
        "device": [perf_df["device"].iloc[0] if "device" in perf_df.columns else "Unknown"],
        "combine_mode": [combine],
        "countries_analyzed": [len(df)]
    })
    return carbon_output, summary

# ------------********------------ 
# ============================== Plot Helpers ======
# ------------********------------ 
plt_kwargs = dict(dpi=140, bbox_inches="tight")

def _boxplot_with_labels(data, labels):
    # Matplotlib 3.9 renamed 'labels' -> 'tick_labels'
    try:
        plt.boxplot(data, tick_labels=labels)
    except TypeError:
        plt.boxplot(data, labels=labels)

def plot_performance(df: pd.DataFrame, outdir: str):
    #  Plot performance metrics for Grover;
    # Runtime vs N (log scale)
    g = df.groupby("N")["runtime_s"].mean().reset_index()
    plt.figure(figsize=(10, 6))
    plt.plot(g["N"], g["runtime_s"], marker="o", linewidth=2, markersize=8)
    plt.title(f"Performance: Runtime vs Search Space Size\n{get_device_name()}")
    plt.xlabel("Search Space Size (N)")
    plt.ylabel("Runtime (s)")
    plt.xscale("log", base=2)
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "perf_runtime_vs_N.png"), **plt_kwargs)
    plt.close()

    # Memory vs N
    g2 = df.groupby("N")["peak_mem_mb"].mean().reset_index()
    plt.figure(figsize=(10, 6))
    plt.plot(g2["N"], g2["peak_mem_mb"], marker="s", linewidth=2, markersize=8)
    plt.title(f"Performance: Memory vs Search Space Size\n{get_device_name()}")
    plt.xlabel("Search Space Size (N)")
    plt.ylabel("Peak Memory (MB)")
    plt.xscale("log", base=2)
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "perf_memory_vs_N.png"), **plt_kwargs)
    plt.close()

    # Success probability vs N
    g3 = df.groupby("N")["accuracy_mean"].mean().reset_index()
    plt.figure(figsize=(10, 6))
    plt.plot(g3["N"], g3["accuracy_mean"], marker="^", linewidth=2, markersize=8, color='green')
    plt.title(f"Performance: Success Probability vs Search Space Size\n{get_device_name()}")
    plt.xlabel("Search Space Size (N)")
    plt.ylabel("Success Probability")
    plt.xscale("log", base=2)
    plt.grid(True, alpha=0.3)
    plt.ylim(0, 1.05)
    plt.savefig(os.path.join(outdir, "perf_success_vs_N.png"), **plt_kwargs)
    plt.close()

    # Iterations vs sqrt(N) scaling
    g4 = df.groupby("N")["iterations"].mean().reset_index()
    plt.figure(figsize=(10, 6))
    plt.plot(g4["N"], g4["iterations"], marker="o", linewidth=2, markersize=8, label="Actual")
    # Add sqrt(N) reference
    sqrt_ref = [n**0.5 for n in g4["N"]]
    plt.plot(g4["N"], sqrt_ref, '--', linewidth=2, label="√N (reference)")
    plt.title(f"Performance: Grover Iterations vs N\n{get_device_name()}")
    plt.xlabel("Search Space Size (N)")
    plt.ylabel("Iterations")
    plt.xscale("log", base=2)
    plt.yscale("log")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "perf_iterations_vs_N.png"), **plt_kwargs)
    plt.close()

# ------------********------------ 
def plot_scalability(df: pd.DataFrame, outdir: str):
    # Plot scalability metrics for Grover
    # Runtime scaling with N (log-log)

    g = df.groupby("N")["runtime_s"].mean().reset_index()
    plt.figure(figsize=(10, 6))
    plt.loglog(g["N"], g["runtime_s"], marker="o", markersize=8)
    plt.title(f"Scalability: Runtime vs Search Space Size (log-log)\n{get_device_name()}")
    plt.xlabel("Search Space Size (N)")
    plt.ylabel("Runtime (s)")
    plt.grid(True, which="both", alpha=0.3)

    # Fit scaling law
    if len(g) > 1:
        x = np.log(g["N"].values)
        y = np.log(g["runtime_s"].values)
        coef = np.polyfit(x, y, 1)
        scaling_exp = coef[0]
        plt.text(0.05, 0.95, f'Scaling: N^{scaling_exp:.2f}',
                transform=plt.gca().transAxes, fontsize=12,
                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8))

    plt.savefig(os.path.join(outdir, "scal_loglog_runtime_vs_N.png"), **plt_kwargs)
    plt.close()

    # Memory scaling with N
    g2 = df.groupby("N")["peak_mem_mb"].mean().reset_index()
    plt.figure(figsize=(10, 6))
    plt.plot(g2["N"], g2["peak_mem_mb"], marker="s", linewidth=2, markersize=8, color='red')
    plt.title(f"Scalability: Memory vs Search Space Size\n{get_device_name()}")
    plt.xlabel("Search Space Size (N)")
    plt.ylabel("Peak Memory (MB)")
    plt.xscale("log", base=2)
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "scal_memory_vs_N.png"), **plt_kwargs)
    plt.close()

    # Query complexity scaling
    g3 = df.groupby("N")["queries"].mean().reset_index()
    plt.figure(figsize=(10, 6))
    plt.loglog(g3["N"], g3["queries"], marker="o", markersize=8, label="Actual")
    # Add O(√N) reference line
    sqrt_line = [n**0.5 for n in g3["N"]]
    plt.loglog(g3["N"], sqrt_line, '--', label="O(√N) reference")
    plt.title(f"Scalability: Query Complexity (log-log)\n{get_device_name()}")
    plt.xlabel("Search Space Size (N)")
    plt.ylabel("Queries")
    plt.legend()
    plt.grid(True, which="both", alpha=0.3)
    plt.savefig(os.path.join(outdir, "scal_queries_vs_N.png"), **plt_kwargs)
    plt.close()

# ------------********------------ 
def plot_reliability(df: pd.DataFrame, outdir: str):
    #  Plot reliability metrics for Grover
    # Success probability distribution by N

    data = [df[df["N"] == n]["accuracy_mean"].values for n in sorted(df["N"].unique())]
    plt.figure(figsize=(10, 6))
    _boxplot_with_labels(data, labels=sorted(df["N"].unique()))
    plt.title(f"Reliability: Success Probability Distribution by N\n{get_device_name()}")
    plt.xlabel("Search Space Size (N)")
    plt.ylabel("Success Probability")
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "rel_success_distribution.png"), **plt_kwargs)
    plt.close()

    # Theory vs Simulation comparison
    g = df.groupby("N").agg({
        "p_success_theory": "mean",
        "p_success_sim": "mean"
    }).reset_index()

    plt.figure(figsize=(10, 6))
    plt.plot(g["N"], g["p_success_theory"], marker="o", linewidth=2, markersize=8, label="Theory")
    plt.plot(g["N"], g["p_success_sim"], marker="s", linewidth=2, markersize=8, label="Simulation")
    plt.title(f"Reliability: Theory vs Simulation Success Probability\n{get_device_name()}")
    plt.xlabel("Search Space Size (N)")
    plt.ylabel("Success Probability")
    plt.xscale("log", base=2)
    plt.ylim(0, 1.05)
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "rel_theory_vs_sim.png"), **plt_kwargs)
    plt.close()

    # Success rate trend
    success_rates = df.groupby('N')['success'].mean().reset_index()
    plt.figure(figsize=(10, 6))
    plt.plot(success_rates['N'], success_rates['success'], marker='o', linewidth=2, markersize=8)
    plt.title(f"Reliability: Success Rate vs Search Space Size\n{get_device_name()}")
    plt.xlabel("Search Space Size (N)")
    plt.ylabel("Success Rate")
    plt.xscale("log", base=2)
    plt.grid(True, alpha=0.3)
    plt.ylim(0, 1.1)
    plt.savefig(os.path.join(outdir, "rel_success_rate.png"), **plt_kwargs)
    plt.close()

    # Error distribution (simulation - theory)
    plt.figure(figsize=(10, 6))
    plt.hist(df["p_error_sim"].values, bins=30, alpha=0.7, edgecolor='black')
    plt.xlabel("Error (Simulation - Theory)")
    plt.ylabel("Frequency")
    plt.title(f"Reliability: Success Probability Error Distribution\n{get_device_name()}")
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "rel_error_distribution.png"), **plt_kwargs)
    plt.close()

# ------------********------------ 
def plot_carbon(df: pd.DataFrame, combine: bool, outdir: str):
    #   Generate carbon footprint plots
    # Top 15 highest emissions

    top = df.nlargest(15, "kgCO2e")
    plt.figure(figsize=(12, 8))
    plt.barh(top["Country"][::-1], top["kgCO2e"][::-1], color='red', alpha=0.7)
    plt.xlabel("kg CO2e (higher = dirtier grid)", fontsize=12)
    plt.title(f"Carbon: Top 15 Highest Emissions\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(outdir, "carbon_top15.png"), **plt_kwargs)
    plt.close()

    # Bottom 15 lowest emissions
    bot = df.nsmallest(15, "kgCO2e")
    plt.figure(figsize=(12, 8))
    plt.barh(bot["Country"][::-1], bot["kgCO2e"][::-1], color='green', alpha=0.7)
    plt.xlabel("kg CO2e (lower = cleaner grid)", fontsize=12)
    plt.title(f"Carbon: Bottom 15 Lowest Emissions\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(outdir, "carbon_bottom15.png"), **plt_kwargs)
    plt.close()

    # Distribution histogram
    plt.figure(figsize=(10, 6))
    plt.hist(df["kgCO2e"], bins=30, alpha=0.7, edgecolor='black', color='orange')
    plt.xlabel("kg CO2e for this experiment", fontsize=12)
    plt.ylabel("Frequency", fontsize=12)
    plt.title(f"Carbon: Emission Distribution\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "carbon_distribution.png"), **plt_kwargs)
    plt.close()

    # CDF plot
    xs = np.sort(df["kgCO2e"].values)
    ys = np.arange(1, len(xs) + 1) / len(xs)
    plt.figure(figsize=(10, 6))
    plt.plot(xs, ys, linewidth=2, color='purple')
    plt.xlabel("kg CO2e", fontsize=12)
    plt.ylabel("CDF", fontsize=12)
    plt.title(f"Carbon: Cumulative Distribution\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "carbon_cdf.png"), **plt_kwargs)
    plt.close()

# ------------********------------ 
# ============================== Utility Functions =====
# ------------********------------ 

def ensure_dir(d: str):
    # Ensure directory exists

    os.makedirs(d, exist_ok=True)

def to_excel(dfs: Dict[str, pd.DataFrame], path: str):
    #  Save multiple DataFrames to Excel with different sheets"""
    with pd.ExcelWriter(path, engine="openpyxl") as w:
        for name, df in dfs.items():
            df.to_excel(w, index=False, sheet_name=name[:31])

# ------------********------------ 
# ============================== Main Experiment Runner 
# ------------********------------ 

def run_quantum_grover_experiment():
    
    # Main Quantum Grover Search experiment runner with hardcoded parameters for Kaggle.
    # Equivalent to: --sizes 8 10 12 14 --marked-count 1 --trials 10 --shots 0
    #               --acc-tol 0.90
    #               --device-power-watts 65 --pue 1.2 --combine
    # Experiment parameters


    sizes = [8, 10, 12, 14]       # Corresponds to N = 256, 1024, 4096, 16384
    trials = 10                   # seeds per N
    marked_count = 1              # number of marked items (typical Grover search)
    shots = 0                     # measurement shots (0 = statevector only)
    acc_tol = 0.90                # accuracy tolerance
    method = "quantum_grover_search"
    workers = 4                   # Number of parallel threads

    # Carbon parameters
    device_power_watts = 65.0
    pue = 1.2
    combine = True

    print(f"🚀 Starting Quantum Grover Search experiments on {get_device_name()}")
    print(f"🔧 Configuration:")
    print(f"   Qubits (n): {sizes}")
    print(f"   Search Space Sizes (N=2^n): {[2**n for n in sizes]}")
    print(f"   Trials per size: {trials}")
    print(f"   Marked items: {marked_count}")
    print(f"   Measurement shots: {shots}")
    print(f"   Accuracy tolerance: {acc_tol}")
    print(f"   Method: {method}")
    print(f"   Workers: {workers}")
    print(f"   Device power: {device_power_watts}W")
    print(f"   PUE: {pue}")
    print(f"   Combine carbon: {combine}")

    # Create output folders
    perf_dir = os.path.join(os.getcwd(), "Performance")
    scal_dir = os.path.join(os.getcwd(), "Scalability")
    rel_dir  = os.path.join(os.getcwd(), "Reliability")
    carb_root = os.path.join(os.getcwd(), "Carbon footprints")
    carb_dir  = os.path.join(carb_root, "carbon_by_country")

    for d in [perf_dir, scal_dir, rel_dir, carb_dir]:
        ensure_dir(d)

    # Prepare jobs
    jobs = []
    for n in sizes:
        N = 2 ** n  # Search space size
        for i in range(trials):
            seed = 1000 + 53 * n + i
            jobs.append((N, marked_count, seed, shots, acc_tol))

    all_rows = []

    def _consume(row):
        """Process completed job results"""
        all_rows.append(row)
        print(f"  ✅ N={row['N']} (n={row['n_bits']}), seed={row['seed']} "
              f"(runtime={row['runtime_s']:.3f}s, success={row['p_success_sim']:.3f}, "
              f"iterations={row['iterations']}, success_flag={row['success']})")

    # Execute jobs with thread-based parallelization
    print(f"🔀 Running {len(jobs)} jobs in parallel with {workers} threads...")

    if workers > 1 and len(jobs) > 1:
        with ThreadPoolExecutor(max_workers=workers) as executor:
            # Submit all jobs
            future_to_job = {executor.submit(run_grover_experiment_thread_safe, job): job for job in jobs}

            # Collect results as they complete
            for future in as_completed(future_to_job):
                try:
                    result = future.result()
                    _consume(result)
                except Exception as e:
                    job = future_to_job[future]
                    print(f"❌ Job failed N={job[0]}, seed={job[2]}: {e}")
    else:
        # Fallback to sequential execution
        for job in jobs:
            try:
                result = run_grover_experiment_thread_safe(job)
                _consume(result)
            except Exception as e:
                print(f"❌ Job failed N={job[0]}, seed={job[2]}: {e}")

    # Check if we have any successful results
    if not all_rows:
        print("💥 CRITICAL: No experiments completed successfully!")
        return None

    perf_df = pd.DataFrame(all_rows)

# ------------********------------ 
    # ---------------- Performance Results ----------------
# ------------********------------ 

    print("📊 Generating Performance results...")
    perf_excel = os.path.join(perf_dir, "performance_results.xlsx")
    perf_agg = perf_df.groupby("N").agg({
        "n_bits": "first",
        "runtime_s": "mean",
        "accuracy_mean": "mean",
        "peak_mem_mb": "mean",
        "iterations": "mean",
        "queries": "mean",
        "queries_theory": "mean",
        "p_success_theory": "mean",
        "p_success_sim": "mean",
        "success": "mean",
        "work_units": "mean"
    }).reset_index()

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "raw_runs": perf_df,
            "aggregated": perf_agg
        }, perf_excel)

    plot_performance(perf_df, perf_dir)

# ------------********------------ 
    # ---------------- Scalability Results ----------------
# ------------********------------ 

    print("📈 Generating Scalability results...")
    scal_excel = os.path.join(scal_dir, "scalability_results.xlsx")
    scal_agg = perf_df.groupby("N").agg({
        "runtime_s": "mean",
        "peak_mem_mb": "mean",
        "iterations": "mean",
        "queries": "mean",
        "work_units": "mean"
    }).reset_index()

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "from_perf_runs": perf_df[["N", "n_bits", "seed", "runtime_s", "peak_mem_mb", "iterations", "queries"]],
            "aggregated": scal_agg
        }, scal_excel)

    plot_scalability(perf_df, scal_dir)

# ------------********------------ 
    # ---------------- Reliability Results ----------------
# ------------********------------ 

    print("🎯 Generating Reliability results...")
    rel_excel = os.path.join(rel_dir, "reliability_results.xlsx")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "fidelity_analysis": perf_df[["N", "n_bits", "seed",
                                          "p_success_theory", "p_success_sim", "p_success_meas",
                                          "p_error_sim", "p_error_meas", "success"]]
        }, rel_excel)

    plot_reliability(perf_df, rel_dir)

# ------------********------------ 
    # ---------------- Carbon Footprint Results ----------------
# ------------********------------ 

    print("🌍 Generating Carbon footprint results...")

    # Load carbon data from Kaggle input directory
    excel_path = "/kaggle/input/masters/Filtered CO2 intensity 236 Countries.xlsx"
    intensity_df = None

    try:
        # Try to load from the exact path
        intensity_df = pd.read_excel(excel_path)
        print(f"✅ Loaded carbon data from: {excel_path}")
        print(f"   Columns found: {list(intensity_df.columns)}")
        print(f"   Countries loaded: {len(intensity_df)}")

        # Auto-detect and process columns
        cols = {c.lower(): c for c in intensity_df.columns}
        cand_country = next((v for k,v in cols.items() if "country" in k or "nation" in k or k=="location"), None)
        if cand_country is None:
            raise ValueError("No 'Country' column found.")

        cand_intensity = next((v for k,v in cols.items() if "intensity" in k or ("co2" in k and ("kwh" in k or "/kwh" in k)) or "kgco2" in k or "gco2" in k), None)

        if cand_intensity is None:
            numeric_cols = [c for c in intensity_df.columns if pd.api.types.is_numeric_dtype(intensity_df[c])]
            if not numeric_cols:
                raise ValueError("No numeric intensity column detected.")
            cand_intensity = numeric_cols[0]

        # Keep only necessary columns
        intensity_df = intensity_df[[cand_country, cand_intensity]].copy()
        intensity_df.columns = ["Country", "Intensity"]

        # Convert gCO2/kWh to kgCO2/kWh if needed
        med = float(intensity_df["Intensity"].dropna().median())
        if med > 50:
            intensity_df["Intensity"] = intensity_df["Intensity"] / 1000.0

        intensity_df = intensity_df.dropna(subset=["Country", "Intensity"]).reset_index(drop=True)
        print(f"✅ Processed carbon data for {len(intensity_df)} countries")

    except Exception as e:
        print(f"❌ ERROR loading carbon data: {e}")
        print("💡 Using sample carbon data as fallback...")
        # Create sample data similar to other codes
        countries = ["France", "Sweden", "Norway", "Switzerland", "Austria", "Germany", "United States", "China", "India"]
        intensities = [52, 41, 32, 45, 62, 385, 389, 537, 708]
        intensity_df = pd.DataFrame({
            "Country": countries,
            "Intensity": [i/1000.0 for i in intensities]  # Convert to kg/kWh
        })

    ensure_dir(carb_dir)
    carbon_df, summary_df = compute_carbon(perf_df, intensity_df,
                                           power_watts=device_power_watts,
                                           pue=pue, combine=combine)
    carb_excel = os.path.join(carb_dir, "carbon_results.xlsx")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "carbon_results": carbon_df,
            "summary": summary_df,
            "intensity_input": intensity_df,
            "performance_reference": perf_df[["N", "n_bits", "seed", "runtime_s"]]
        }, carb_excel)

    # Generate carbon plots
    plot_carbon(carbon_df, combine, carb_dir)
    print(f"✅ Carbon analysis complete: {len(carbon_df)} entries")

    # Final summary
    print("\n" + "="*60)
    print("🎉 QUANTUM GROVER SEARCH EXPERIMENT COMPLETE - RESULTS SUMMARY")
    print("="*60)
    print(f"📁 Performance:     {perf_excel}")
    print(f"📁 Scalability:     {scal_excel}")
    print(f"📁 Reliability:     {rel_excel}")
    print(f"📁 Carbon:          {carb_excel}")
    print(f"🖥️  Device:          {get_device_name()}")
    print(f"📊 Total runs:      {len(perf_df)}")
    print(f"⚡ Total runtime:   {perf_df['runtime_s'].sum():.2f}s")
    print(f"🔬 Qubit range:     {sorted(perf_df['n_bits'].unique())}")
    print(f"🎯 Success rate:    {perf_df['success'].mean() * 100:.1f}%")
    print(f"🔢 Total iterations: {perf_df['iterations'].sum():,}")
    print(f"🔍 Average speedup factor: ~{np.mean([2**n/df['iterations'].mean() for n, df in perf_df.groupby('n_bits')]):.2f}x")

    print(f"\n📂 All results saved to:")
    for d in [perf_dir, scal_dir, rel_dir, carb_dir]:
        print(f"   • {d}")

    return perf_df

# ============================================================
# ------------********------------  Main execution for Kaggle
# ============================================================
if __name__ == "__main__":
    # Clean up GPU state
    safe_gpu_cleanup()

    print("🚀 Starting Quantum Grover Search Benchmark on Kaggle")
    print("=" * 50)

    # Run the complete experiment
    results_df = run_quantum_grover_experiment()

    if results_df is not None:
        # Display final results summary
        print("\n📊 FINAL RESULTS SUMMARY")
        print("=" * 30)
        print(f"Total experiments: {len(results_df)}")
        print(f"Qubit range: {sorted(results_df['n_bits'].unique())}")
        print(f"Search space sizes: {sorted(results_df['N'].unique())}")
        print(f"Average runtime: {results_df['runtime_s'].mean():.6f}s")
        print(f"Success rate: {results_df['success'].mean() * 100:.1f}%")
        print(f"Average success probability: {results_df['p_success_sim'].mean():.3f}")
        print(f"Average iterations per run: {results_df['iterations'].mean():.1f}")
        print(f"Expected quantum speedup: O(√N) over classical O(N)")
        print(f"Device used: {get_device_name()}")

        # Show folder structure
        print("\n📁 GENERATED OUTPUT STRUCTURE:")
        base_dir = '/kaggle/working'
        for root, dirs, files in os.walk(base_dir):
            # Only show our output directories
            if any(x in root for x in ['Performance', 'Scalability', 'Reliability', 'Carbon footprints']):
                level = root.replace(base_dir, '').count(os.sep)
                indent = ' ' * 2 * level
                print(f'{indent}📁 {os.path.basename(root)}/')
                sub_indent = ' ' * 2 * (level + 1)
                for file in files:
                    if file.endswith(('.xlsx', '.png')):
                        file_path = os.path.join(root, file)
                        size = os.path.getsize(file_path) / 1024  # KB
                        icon = "📊" if file.endswith('.xlsx') else "🖼️"
                        print(f'{sub_indent}{icon} {file} ({size:.1f} KB)')

        print("\n✅ All Quantum Grover Search deliverables generated successfully!")
        print("   • Performance/performance_results.xlsx + perf_*.png")
        print("   • Scalability/scalability_results.xlsx + scal_*.png")
        print("   • Reliability/reliability_results.xlsx + rel_*.png")
        print("   • Carbon footprints/carbon_by_country/carbon_results.xlsx + carbon_*.png")
    else:
        print("❌ Quantum Grover Search benchmark failed - no results generated")

