#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------------------------------------------------
# GPU-accelerated Empirical Evaluation: Simon's Algorithm (Noiseless) – Quantum Baseline
# ----------------------------------------------------------------------------------------------------------------

# Notes: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# Code focuses on Performance, Scalability, Reliability, Carbon footprints
# Output folders are:
    #   Performance = runtime
    #   Scalability = growth of runtime as N increases (digits/bits).
    #   Reliability = success rate + dispersion across repetitions.
    #   Carbon footprints = derived *only* from PERFORMANCE totals
    #   (sum of successful wall-times), device power 65 Watts fixed for comparasion, PUE 1.2 fixed, 
    #   country carbon intensity (kg CO2/kWh). I did not use scalability or reliability results for CO2.

#      Carbon Data File: 
#      Uses ONLY Performance runtimes (not Scalability/Reliability), 
#      Placed on my Desktop Excel of country intensities "Filtered CO2 intensity 236 Countries.xlsx"
#      (CSV or XLSX; year column optional. I have selected --year-select latest.)
# ----------------------------------------------------------------------------------------------------------------

"""7 Simon
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/i222070tabidahusmani/7-simon.6afbc320-28a0-453a-90e7-98aa55520d1f.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20251117/auto/storage/goog4_request%26X-Goog-Date%3D20251117T135400Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3Db0378e2bd319edf84ae000274f64b2e1a2f6b0532b616924b221f3d47022bf23458082a20997fa13cff489802f7ee7ea71b59293be1d44e5e671f548384c1635c8bd9f29050a25837ee82981aff773dc647a57c4e93e2a6379c696cf72d2ccf166d354d4e39badb227f5cefccc93ff6dfe11d759df1aec0b59370d5535ae205f84041f94f79000ae148149f85049e606bc35a6a02281f6cdc547cd216c0a0eb02c978e988266cef30f95f623c2c006e06368ff88908d3dd58590d89fdece192d57b7bd16dbdfc2edaa3d4abad461efc1df1be741cadd63a3ea8ddbddb423bc1e089b5e088ad0405328ec254afb96a26a18b357c0680f87363c868e74a7c977a7
"""


"""
GPU-accelerated Empirical Evaluation: Simon's Algorithm (Noiseless) – Quantum Baseline

Folders created in the current directory:
  Performance/, Scalability/, Reliability/, Carbon footprints/<outdir>/
"""


# ------------********------------ Imports
import os, sys, time, tracemalloc, pathlib, warnings, math
from dataclasses import dataclass
from typing import List, Tuple, Dict, Any
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed

# ============================================================
# ------------********------------ GPU Setup and Dependencies
# ============================================================
print("🔍 Checking GPU availability...")

HAS_GPU = False
cp = None

try:
    import cupy as cp
    # Test if GPU is available and working
    with cp.cuda.Device(0):
        # Simple test to verify GPU functionality
        test_array = cp.zeros(10, dtype=cp.float32)
        result = cp.sum(test_array)
        HAS_GPU = True
        print(f"✅ GPU detected: {cp.cuda.runtime.getDeviceProperties(0)['name'].decode()}")
        print(f"   Memory: {cp.cuda.Device().mem_info[1] / 1e9:.2f} GB")
        print(f"   Compute Capability: {cp.cuda.runtime.getDeviceProperties(0)['major']}.{cp.cuda.runtime.getDeviceProperties(0)['minor']}")
except ImportError:
    print("❌ CuPy not available, falling back to NumPy")
    import numpy as cp
except Exception as e:
    print(f"⚠️  GPU setup failed: {e}, falling back to NumPy")
    import numpy as cp

# If GPU failed, use NumPy
if not HAS_GPU:
    import numpy as cp
    print("🔄 Using NumPy (CPU) backend")

# Install required packages
#This utility function checks for required Python packages and installs any that are missing at runtime.
#It attempts a quiet pip installation and reports errors without interrupting execution.
#It then imports numerical, data processing, and plotting libraries and configures matplotlib for headless use.
def _ensure(pkgs: List[str]):
    import importlib, subprocess
    missing = []
    for p in pkgs:
        try:
            importlib.import_module(p)
        except ImportError:
            missing.append(p)
    if missing:
        print(f"[setup] Installing missing packages: {missing}")
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *missing])
        except Exception as e:
            print(f"[setup] Auto-install failed: {e}")

_ensure(["pandas", "matplotlib", "openpyxl", "psutil"])

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# GPU utility functions
def get_device_name() -> str:
    """Get current device name"""
    if HAS_GPU:
        try:
            return f"GPU: {cp.cuda.runtime.getDeviceProperties(0)['name'].decode()}"
        except:
            return "GPU: Unknown"
    return "CPU: NumPy"

def safe_gpu_cleanup():
    """Safely cleanup GPU memory"""
    if HAS_GPU:
        try:
            cp.get_default_memory_pool().free_all_blocks()
        except:
            pass

# Thread-safe GPU operations
_gpu_lock = threading.Lock()

def run_experiment_thread_safe(args):
    """
    Thread-safe GPU experiment runner.
    Uses a lock to prevent multiple threads from accessing GPU simultaneously.
    """
    n, seed = args
    with _gpu_lock:  # Ensure only one thread uses GPU at a time
        return _run_single_experiment(n, seed)


# ------------********------------
 # Utilities: GF(2) linear algebra 
# ------------********------------

#This def gf2_rank () function computes the rank of a binary matrix over GF(2) using Gaussian elimination.
#It ensures compatibility by converting GPU arrays to NumPy arrays before processing.
#It returns the number of linearly independent rows found during elimination.

def gf2_rank(A: np.ndarray) -> int:
    """Return rank of binary matrix A over GF(2)."""
    # Ensure we're working with NumPy arrays for linear algebra
    if HAS_GPU and isinstance(A, cp.ndarray):
        A = cp.asnumpy(A)

    A = (A.astype(np.uint8) & 1).copy()
    m, n = A.shape
    row = 0
    for col in range(n):
        # find pivot
        pivot = None
        for r in range(row, m):
            if A[r, col]:
                pivot = r; break
        if pivot is None:
            continue
        if pivot != row:
            A[[row, pivot]] = A[[pivot, row]]
        # eliminate in all other rows
        for r in range(m):
            if r != row and A[r, col]:
                A[r, :] ^= A[row, :]
        row += 1
        if row == m:
            break
    return row

#def gf2_solve_homogeneous_one () function solves a homogeneous linear system over GF(2) 
#   and returns one valid non-zero solution.
#It converts GPU arrays to NumPy for compatibility and 
#   reduces the matrix to row-reduced echelon form.
#It constructs the solution by assigning a free variable and back-substituting pivot values.

def gf2_solve_homogeneous_one(A: np.ndarray) -> np.ndarray:
    """
    Solve A s = 0 over GF(2) and return one non-zero solution (if exists).
    Assumes nullity >= 1; for Simon we expect rank = n-1 so nullity = 1.
    """
    # Ensure we're working with NumPy arrays for linear algebra
    if HAS_GPU and isinstance(A, cp.ndarray):
        A = cp.asnumpy(A)

    A = (A.astype(np.uint8) & 1).copy()
    m, n = A.shape
    row = 0
    pivots = []
    for col in range(n):
        pivot = None
        for r in range(row, m):
            if A[r, col]:
                pivot = r; break
        if pivot is None:
            continue
        if pivot != row:
            A[[row, pivot]] = A[[pivot, row]]
        for r in range(m):
            if r != row and A[r, col]:
                A[r, :] ^= A[row, :]
        pivots.append(col)
        row += 1
        if row == m:
            break

    free = [c for c in range(n) if c not in pivots]
    s = np.zeros(n, dtype=np.uint8)
    if not free:
        return s  # only zero solution
    fc = free[0]          # only one free var when rank = n-1
    s[fc] = 1
    # back-substitute pivot variables from RREF
    for r in range(len(pivots)-1, -1, -1):
        pc = pivots[r]
        val = 0
        for j in range(pc+1, n):
            if A[r, j] and s[j]:
                val ^= 1
        s[pc] = val
    return s

# ------------********------------
# Ideal Simon measurement sampler 
# ------------********------------

# def sample_y_orthogonal_to_s(n: int, s: np.ndarray, rng: np.random.Generator) -> np.ndarray: 
# It samples a binary vector that is orthogonal to a given secret vector over GF(2).
#It computes the dot product modulo two using explicit bitwise operations for compatibility.
#It repeats sampling until a valid orthogonal vector is found and returns it.

def sample_y_orthogonal_to_s(n: int, s: np.ndarray, rng: np.random.Generator) -> np.ndarray:
    """Sample y uniformly from { y ∈ {0,1}^n : y·s = 0 mod 2 }."""
    while True:
        # Generate random binary vector
        y = rng.integers(0, 2, size=n, dtype=np.uint8)

        # Compute dot product mod 2 (y·s mod 2)
        # Use standard Python operations to avoid GPU-CPU compatibility issues
        dot_product = 0
        for i in range(n):
            dot_product ^= (y[i] & s[i])  # Bitwise AND then XOR for mod 2

        if dot_product == 0:
            return y

#simon_quantum_noiseless function simulates an ideal noiseless quantum Simon algorithm 
#   using classical post-processing.
#It iteratively samples vectors orthogonal to the secret until sufficient linear independence is achieved.
#It reconstructs and verifies the hidden string, 
#    returning the guess, query count, and success flag.

def simon_quantum_noiseless(n: int, s: np.ndarray, seed: int,
                            max_rounds: int | None = None):
    """
    Ideal Simon algorithm: collect random y with y·s=0 until rank(Y)=n-1.
    One oracle query per round.
    """
    if max_rounds is None:
        max_rounds = 4 * n  # generous cap; expected O(n) rounds

    rng = np.random.default_rng(seed)
    Ys = []
    rank = 0
    queries = 0
    for _ in range(max_rounds):
        y = sample_y_orthogonal_to_s(n, s, rng)
        Ys.append(y)
        queries += 1

        # Convert to appropriate array type for linear algebra
        Y_matrix = np.array(Ys, dtype=np.uint8)
        rank = gf2_rank(Y_matrix)

        if rank >= n - 1:
            break

    if rank < n - 1:
        return np.zeros(n, dtype=np.uint8), queries, False

    s_guess = gf2_solve_homogeneous_one(np.array(Ys, dtype=np.uint8))

    # Compare arrays element-wise
    success = True
    for i in range(n):
        if s_guess[i] != s[i]:
            success = False
            break

    return s_guess, queries, success

def _run_single_experiment(n: int, seed: int) -> dict:
    """
    Core experiment logic - run single Simon's algorithm experiment.
    """
    rng = np.random.default_rng(seed)
    # Generate non-zero hidden string s
    s = np.zeros(n, dtype=np.uint8)
    while not s.any():
        s = rng.integers(0, 2, size=n, dtype=np.uint8)

    tracemalloc.start()
    t0 = time.perf_counter()
    s_guess, queries, success = simon_quantum_noiseless(n, s, seed=seed)
    runtime = time.perf_counter() - t0
    _, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    # Cleanup GPU memory
    safe_gpu_cleanup()

    return {
        "n": n,
        "seed": seed,
        "queries_used": int(queries),
        "runtime_s": float(runtime),
        "peak_mem_mb": float(peak / (1024**2)),
        "correct": bool(success),
        "device": get_device_name()
    }

# ------------********------------
#           Carbon I/O 
# ------------********------------

def resolve_excel_path(excel_arg: str) -> str:
    p = pathlib.Path(excel_arg)
    if p.is_absolute() and p.exists():
        return str(p)
    desktop = pathlib.Path.home() / "Desktop" / excel_arg
    return str(desktop if desktop.exists() else p)

def load_carbon_excel(path: str, year_select: str = "latest") -> pd.DataFrame:
    df = pd.read_excel(path)
    cols = {c.lower(): c for c in df.columns}
    cand_country = next((v for k, v in cols.items() if "country" in k or "nation" in k or k == "location"), None)
    if cand_country is None:
        raise ValueError("No 'Country' column found.")
    cand_year = next((v for k, v in cols.items() if "year" in k or "date" in k), None)
    cand_intensity = next((v for k, v in cols.items()
                           if "intensity" in k or ("co2" in k and "kwh" in k) or "kgco2" in k or "gco2" in k), None)
    if cand_intensity is None:
        numeric_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
        if cand_year in numeric_cols:
            numeric_cols.remove(cand_year)
        if not numeric_cols:
            raise ValueError("No numeric intensity column detected.")
        cand_intensity = numeric_cols[0]
    keep = [cand_country] + ([cand_year] if cand_year else []) + [cand_intensity]
    df = df[keep].copy()
    df.columns = ["Country", "Year", "Intensity"] if len(keep) == 3 else ["Country", "Intensity"]
    if "Year" in df.columns and year_select.lower() == "latest":
        df = df.sort_values(["Country", "Year"]).groupby("Country", as_index=False).tail(1)

    # Heuristic unit fix: if median looks like g/kWh, convert to kg/kWh
    med = float(df["Intensity"].dropna().median())
    if med > 50:
        df["Intensity"] = df["Intensity"] / 1000.0

    return df.dropna(subset=["Country", "Intensity"]).reset_index(drop=True)


#The following function computes carbon emissions based on total experiment runtime and country-level intensity data.
#It calculates energy usage and per-country CO2 emissions while always returning country-wise results.
#It produces a summary table with runtime, energy, emissions statistics, and configuration metadata.
def compute_carbon(perf_df: pd.DataFrame, intensity_df: pd.DataFrame,
                   power_watts: float, pue: float, combine: bool) -> tuple[pd.DataFrame, pd.DataFrame]:
    total_runtime_s = float(perf_df["runtime_s"].sum())
    kWh_total = power_watts * pue * total_runtime_s / 3_600_000.0
    df = intensity_df.copy()
    df["kWh"] = kWh_total
    df["kgCO2e"] = df["Intensity"] * df["kWh"]

    # ALWAYS return country-wise results (ignore combine parameter)
    carbon_output = df.sort_values("kgCO2e", ascending=False)

    summary = pd.DataFrame({
        "total_runtime_s": [total_runtime_s],
        "power_watts": [power_watts],
        "PUE": [pue],
        "kWh_total": [kWh_total],
        "median_intensity_kg_per_kWh": [float(df["Intensity"].median())],
        "mean_kgCO2e_across_countries": [float(df["kgCO2e"].mean())],
        "device": [perf_df["device"].iloc[0] if "device" in perf_df.columns else "Unknown"],
        "combine_mode": [combine],
        "countries_analyzed": [len(df)]
    })
    return carbon_output, summary

# ------------********------------
#            Plot Helpers 
# ------------********------------

plt_kwargs = dict(dpi=140, bbox_inches="tight")

def _boxplot_with_labels(data, labels):
    # Matplotlib 3.9 renamed 'labels' -> 'tick_labels'
    try:
        plt.boxplot(data, tick_labels=labels)
    except TypeError:
        plt.boxplot(data, labels=labels)

# ------------********------------
def plot_performance(df: pd.DataFrame, outdir: str):
    g = df.groupby("n")["runtime_s"].mean().reset_index()
    plt.figure()
    plt.plot(g["n"], g["runtime_s"], marker="o", linewidth=2, markersize=8)
    plt.title(f"Performance: Runtime vs Input Size\n{get_device_name()}")
    plt.xlabel("Input Size n (bits)")
    plt.ylabel("Runtime (s)")
    plt.grid(True)
    plt.savefig(os.path.join(outdir, "perf_runtime_vs_n.png"), **plt_kwargs)
    plt.close()

    g2 = df.groupby("n")["queries_used"].mean().reset_index()
    plt.figure()
    plt.plot(g2["n"], g2["queries_used"], marker="s", linewidth=2, markersize=8)
    plt.title(f"Performance: Mean Queries vs n\n{get_device_name()}")
    plt.xlabel("Input Size n (bits)")
    plt.ylabel("Mean Queries Used")
    plt.grid(True)
    plt.savefig(os.path.join(outdir, "perf_queries_vs_n.png"), **plt_kwargs)
    plt.close()


# ------------********------------

def plot_scalability(df: pd.DataFrame, outdir: str):
    g = df.groupby("n")["peak_mem_mb"].mean().reset_index()
    plt.figure()
    plt.plot(g["n"], g["peak_mem_mb"], marker="^", linewidth=2, markersize=8, color='green')
    plt.title(f"Scalability: Memory vs Input Size\n{get_device_name()}")
    plt.xlabel("Input Size n (bits)")
    plt.ylabel("Memory (MB)")
    plt.grid(True)
    plt.savefig(os.path.join(outdir, "scal_memory_vs_n.png"), **plt_kwargs)
    plt.close()

    g2 = df.groupby("n")["runtime_s"].mean().reset_index()
    plt.figure()
    plt.loglog(g2["n"], g2["runtime_s"], marker="o", linewidth=2, markersize=8)
    plt.title(f"Scalability: Runtime (log-log)\n{get_device_name()}")
    plt.xlabel("n")
    plt.ylabel("Runtime (s)")
    plt.grid(True, which="both")
    plt.savefig(os.path.join(outdir, "scal_loglog_runtime.png"), **plt_kwargs)
    plt.close()


# ------------********------------

def plot_reliability(df: pd.DataFrame, outdir: str):
    data = [df[df["n"] == n]["queries_used"].values for n in sorted(df["n"].unique())]
    plt.figure()
    _boxplot_with_labels(data, labels=sorted(df["n"].unique()))
    plt.title(f"Reliability: Queries Distribution by n\n{get_device_name()}")
    plt.xlabel("Input Size n (bits)")
    plt.ylabel("Queries Used")
    plt.grid(True)
    plt.savefig(os.path.join(outdir, "rel_queries_boxplot.png"), **plt_kwargs)
    plt.close()

    g = df.groupby("n")["correct"].mean().reset_index()
    plt.figure()
    plt.plot(g["n"], g["correct"], marker="o", linewidth=2, markersize=8)
    plt.title(f"Reliability: Success Rate vs n\n{get_device_name()}")
    plt.xlabel("n")
    plt.ylabel("Success Rate")
    plt.grid(True)
    plt.savefig(os.path.join(outdir, "rel_success_vs_n.png"), **plt_kwargs)
    plt.close()


# ------------********------------

#The following blocks generate visualizations for carbon emissions including 
#   lowest-emission countries, distribution, and cumulative distribution.
#Code creates and saves bar charts, histograms, and CDF plots to 
#   summarize carbon impact results.
#It also labels plots with device information and stores all figures in the specified output directory.

def plot_carbon(df: pd.DataFrame, combine: bool, outdir: str):
    """Generate carbon footprint plots - ALWAYS country-wise"""
    # Top 15 highest emissions
    top = df.nlargest(15, "kgCO2e")
    plt.figure(figsize=(12, 8))
    plt.barh(top["Country"][::-1], top["kgCO2e"][::-1], color='red', alpha=0.7)
    plt.xlabel("kg CO2e (higher = dirtier grid)", fontsize=12)
    plt.title(f"Carbon: Top 15 Highest Emissions\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(outdir, "carbon_top15.png"), **plt_kwargs)
    plt.close()

    # Bottom 15 lowest emissions
    bot = df.nsmallest(15, "kgCO2e")
    plt.figure(figsize=(12, 8))
    plt.barh(bot["Country"][::-1], bot["kgCO2e"][::-1], color='green', alpha=0.7)
    plt.xlabel("kg CO2e (lower = cleaner grid)", fontsize=12)
    plt.title(f"Carbon: Bottom 15 Lowest Emissions\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(outdir, "carbon_bottom15.png"), **plt_kwargs)
    plt.close()

    # Distribution histogram
    plt.figure(figsize=(10, 6))
    plt.hist(df["kgCO2e"], bins=30, alpha=0.7, edgecolor='black', color='orange')
    plt.xlabel("kg CO2e for this experiment", fontsize=12)
    plt.ylabel("Frequency", fontsize=12)
    plt.title(f"Carbon: Emission Distribution\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "carbon_distribution.png"), **plt_kwargs)
    plt.close()

    # CDF plot
    xs = np.sort(df["kgCO2e"].values)
    ys = np.arange(1, len(xs) + 1) / len(xs)
    plt.figure(figsize=(10, 6))
    plt.plot(xs, ys, linewidth=2, color='purple')
    plt.xlabel("kg CO2e", fontsize=12)
    plt.ylabel("CDF", fontsize=12)
    plt.title(f"Carbon: Cumulative Distribution\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "carbon_cdf.png"), **plt_kwargs)
    plt.close()

# ------------********------------
#            Utility Functions 
# ------------********------------
def ensure_dir(d: str):
    """Ensure directory exists"""
    os.makedirs(d, exist_ok=True)

def to_excel(dfs: Dict[str, pd.DataFrame], path: str):
    """Save multiple DataFrames to Excel with different sheets"""
    with pd.ExcelWriter(path, engine="openpyxl") as w:
        for name, df in dfs.items():
            df.to_excel(w, index=False, sheet_name=name[:31])


# ------------********------------
#        Main Experiment Runner
# ------------********------------

#def run_simon_experiment(): runs Simon’s algorithm experiments with fixed parameters suitable for a Kaggle environment.
#It configures experiment sizes, trials, parallel workers, and carbon settings, printing a detailed setup summary.
#It creates output directories and prepares job lists for executing multiple Simon experiment runs.

def run_simon_experiment():
    """
    Main Simon's algorithm experiment runner with hardcoded parameters for Kaggle.
    Equivalent to: --sizes 6 8 10 --trials 10 --method simon
                   --device-power-watts 65 --pue 1.2 --combine
    """
    # Experiment parameters
    sizes = [6, 8, 10]
    trials = 10  # trials per size
    method = "simon"
    workers = 4  # Number of parallel threads

    # Carbon parameters
    device_power_watts = 65.0
    pue = 1.2
    combine = True

    print(f"🚀 Starting Simon's Algorithm experiments on {get_device_name()}")
    print(f"🔧 Configuration:")
    print(f"   Input sizes: {sizes}")
    print(f"   Trials per size: {trials}")
    print(f"   Method: {method}")
    print(f"   Workers: {workers}")
    print(f"   Device power: {device_power_watts}W")
    print(f"   PUE: {pue}")
    print(f"   Combine carbon: {combine}")

    # Create output folders
    perf_dir = os.path.join(os.getcwd(), "Performance")
    scal_dir = os.path.join(os.getcwd(), "Scalability")
    rel_dir  = os.path.join(os.getcwd(), "Reliability")
    carb_root = os.path.join(os.getcwd(), "Carbon footprints")
    carb_dir  = os.path.join(carb_root, "carbon_by_country")

    for d in [perf_dir, scal_dir, rel_dir, carb_dir]:
        ensure_dir(d)

    # Prepare jobs
    jobs = []
    for n in sizes:
        for i in range(trials):
            jobs.append((n, 1000 + 17 * n + i))

    all_rows = []

    def _consume(row):
        """Process completed job results"""
        all_rows.append(row)
        print(f"  ✅ n={row['n']}, seed={row['seed']} (queries={row['queries_used']}, runtime={row['runtime_s']:.6f}s, correct={row['correct']})")

    # Execute jobs with thread-based parallelization
    print(f"🔀 Running {len(jobs)} jobs in parallel with {workers} threads...")

    if workers > 1 and len(jobs) > 1:
        with ThreadPoolExecutor(max_workers=workers) as executor:
            # Submit all jobs
            future_to_job = {executor.submit(run_experiment_thread_safe, job): job for job in jobs}

            # Collect results as they complete
            for future in as_completed(future_to_job):
                try:
                    result = future.result()
                    _consume(result)
                except Exception as e:
                    job = future_to_job[future]
                    print(f"❌ Job failed n={job[0]}, seed={job[1]}: {e}")
    else:
        # Fallback to sequential execution
        for job in jobs:
            result = run_experiment_thread_safe(job)
            _consume(result)

    # Check if we have any successful results
    if not all_rows:
        print("❌ All jobs failed! Running sequentially as fallback...")
        for job in jobs:
            try:
                result = _run_single_experiment(job[0], job[1])
                _consume(result)
            except Exception as e:
                print(f"❌ Sequential fallback also failed for n={job[0]}, seed={job[1]}: {e}")

    if not all_rows:
        print("💥 CRITICAL: No experiments completed successfully!")
        return None

    perf_df = pd.DataFrame(all_rows)

# ------------********------------
    # ---------------- Performance Results 
# ------------********------------

    print("📊 Generating Performance results...")
    perf_excel = os.path.join(perf_dir, "performance_results.xlsx")
    perf_agg = perf_df.groupby("n").agg({
        "runtime_s": "mean",
        "queries_used": "mean",
        "peak_mem_mb": "mean",
        "correct": "mean"
    }).reset_index()

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "raw_runs": perf_df,
            "aggregated": perf_agg
        }, perf_excel)

    plot_performance(perf_df, perf_dir)

# ------------********------------
    # ---------------- Scalability Results ----------------
# ------------********------------

    print("📈 Generating Scalability results...")
    scal_excel = os.path.join(scal_dir, "scalability_results.xlsx")
    scal_agg = perf_df.groupby("n").agg({
        "runtime_s": "mean",
        "peak_mem_mb": "mean",
        "queries_used": "mean"
    }).reset_index()

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "from_perf_runs": perf_df[["n", "seed", "runtime_s", "peak_mem_mb", "queries_used"]],
            "aggregated": scal_agg
        }, scal_excel)

    plot_scalability(perf_df, scal_dir)

# ------------********------------
    # ---------------- Reliability Results ----------------
# ------------********------------

    print("🎯 Generating Reliability results...")
    rel_excel = os.path.join(rel_dir, "reliability_results.xlsx")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "correctness_analysis": perf_df[["n", "seed", "queries_used", "correct"]]
        }, rel_excel)

    plot_reliability(perf_df, rel_dir)

# ------------********------------
    # ---------------- Carbon Footprint Results ----------------
# ------------********------------

    print("🌍 Generating Carbon footprint results...")

    # Load carbon data from Kaggle input directory
    excel_path = "/kaggle/input/masters/Filtered CO2 intensity 236 Countries.xlsx"
    intensity_df = None

    try:
        # Try to load from the exact path
        intensity_df = pd.read_excel(excel_path)
        print(f"✅ Loaded carbon data from: {excel_path}")
        print(f"   Columns found: {list(intensity_df.columns)}")
        print(f"   Countries loaded: {len(intensity_df)}")

        # Auto-detect and process columns
        cols = {c.lower(): c for c in intensity_df.columns}
        cand_country = next((v for k,v in cols.items() if "country" in k or "nation" in k or k=="location"), None)
        if cand_country is None:
            raise ValueError("No 'Country' column found.")

        cand_intensity = next((v for k,v in cols.items() if "intensity" in k or ("co2" in k and ("kwh" in k or "/kwh" in k)) or "kgco2" in k or "gco2" in k), None)

        if cand_intensity is None:
            numeric_cols = [c for c in intensity_df.columns if pd.api.types.is_numeric_dtype(intensity_df[c])]
            if not numeric_cols:
                raise ValueError("No numeric intensity column detected.")
            cand_intensity = numeric_cols[0]

        # Keep only necessary columns
        intensity_df = intensity_df[[cand_country, cand_intensity]].copy()
        intensity_df.columns = ["Country", "Intensity"]

        # Convert gCO2/kWh to kgCO2/kWh if needed
        med = float(intensity_df["Intensity"].dropna().median())
        if med > 50:
            intensity_df["Intensity"] = intensity_df["Intensity"] / 1000.0

        intensity_df = intensity_df.dropna(subset=["Country", "Intensity"]).reset_index(drop=True)
        print(f"✅ Processed carbon data for {len(intensity_df)} countries")

    except Exception as e:
        print(f"❌ ERROR loading carbon data: {e}")
        print("💡 Using sample carbon data as fallback...")
        # Create sample data similar to other codes
        countries = ["France", "Sweden", "Norway", "Switzerland", "Austria", "Germany", "United States", "China", "India"]
        intensities = [52, 41, 32, 45, 62, 385, 389, 537, 708]
        intensity_df = pd.DataFrame({
            "Country": countries,
            "Intensity": [i/1000.0 for i in intensities]  # Convert to kg/kWh
        })

    ensure_dir(carb_dir)
    carbon_df, summary_df = compute_carbon(perf_df, intensity_df,
                                           power_watts=device_power_watts,
                                           pue=pue, combine=combine)
    carb_excel = os.path.join(carb_dir, "carbon_results.xlsx")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "carbon_results": carbon_df,
            "summary": summary_df,
            "intensity_input": intensity_df,
            "performance_reference": perf_df[["n", "seed", "runtime_s"]]
        }, carb_excel)

    # Generate carbon plots
    plot_carbon(carbon_df, combine, carb_dir)
    print(f"✅ Carbon analysis complete: {len(carbon_df)} entries")

    # Final summary
    print("\n" + "="*60)
    print("🎉 SIMON'S ALGORITHM EXPERIMENT COMPLETE - RESULTS SUMMARY")
    print("="*60)
    print(f"📁 Performance:     {perf_excel}")
    print(f"📁 Scalability:     {scal_excel}")
    print(f"📁 Reliability:     {rel_excel}")
    print(f"📁 Carbon:          {carb_excel}")
    print(f"🖥️  Device:          {get_device_name()}")
    print(f"📊 Total runs:      {len(perf_df)}")
    print(f"⚡ Total runtime:   {perf_df['runtime_s'].sum():.2f}s")
    print(f"🔬 Input sizes:     {sorted(perf_df['n'].unique())}")
    print(f"🎯 Success rate:    {perf_df['correct'].mean() * 100:.1f}%")
    print(f"📈 Mean queries:    {perf_df['queries_used'].mean():.1f}")

    print(f"\n📂 All results saved to:")
    for d in [perf_dir, scal_dir, rel_dir, carb_dir]:
        print(f"   • {d}")

    return perf_df

# ============================================================
#                       Main execution for Kaggle
# ============================================================

#The following code block defines the script entry point and 
#    ensures GPU resources are safely cleaned before execution.
#It launches the full Simon’s algorithm benchmark and 
#    prints a startup banner.
#It runs the experiment and checks whether results were successfully generated.

if __name__ == "__main__":
    # Clean up GPU state
    safe_gpu_cleanup()

    print("🚀 Starting Simon's Algorithm Quantum Benchmark on Kaggle")
    print("=" * 50)

    # Run the complete experiment
    results_df = run_simon_experiment()

    if results_df is not None:

# ------------********------------ Display final results summary

        print("\n📊 FINAL RESULTS SUMMARY")
        print("=" * 30)
        print(f"Total experiments: {len(results_df)}")
        print(f"Input sizes tested: {sorted(results_df['n'].unique())}")
        print(f"Average runtime: {results_df['runtime_s'].mean():.6f}s")
        print(f"Success rate: {results_df['correct'].mean() * 100:.1f}%")
        print(f"Average queries: {results_df['queries_used'].mean():.1f}")
        print(f"Device used: {get_device_name()}")

# ------------********------------ Show folder structure

        print("\n📁 GENERATED OUTPUT STRUCTURE:")
        base_dir = '/kaggle/working'
        for root, dirs, files in os.walk(base_dir):
            # Only show our output directories
            if any(x in root for x in ['Performance', 'Scalability', 'Reliability', 'Carbon footprints']):
                level = root.replace(base_dir, '').count(os.sep)
                indent = ' ' * 2 * level
                print(f'{indent}📁 {os.path.basename(root)}/')
                sub_indent = ' ' * 2 * (level + 1)
                for file in files:
                    if file.endswith(('.xlsx', '.png')):
                        file_path = os.path.join(root, file)
                        size = os.path.getsize(file_path) / 1024  # KB
                        icon = "📊" if file.endswith('.xlsx') else "🖼️"
                        print(f'{sub_indent}{icon} {file} ({size:.1f} KB)')

        print("\n✅ All Simon's Algorithm deliverables generated successfully!")
        print("   • Performance/performance_results.xlsx + perf_*.png")
        print("   • Scalability/scalability_results.xlsx + scal_*.png")
        print("   • Reliability/reliability_results.xlsx + rel_*.png")
        print("   • Carbon footprints/carbon_by_country/carbon_results.xlsx + carbon_*.png")
    else:
        print("❌ Simon's Algorithm benchmark failed - no results generated")

