#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# ----------------------------------------------------------------------------------------------------------------
# GPU-accelerated Quantum Fourier Transform (QFT)
# ----------------------------------------------------------------------------------------------------------------

# Notes: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# Code focuses on Performance, Scalability, Reliability, Carbon footprints
# Output folders are:
    #   Performance = runtime
    #   Scalability = growth of runtime as N increases (digits/bits).
    #   Reliability = success rate + dispersion across repetitions.
    #   Carbon footprints = derived *only* from PERFORMANCE totals
    #   (sum of successful wall-times), device power 65 Watts fixed for comparasion, PUE 1.2 fixed, 
    #   country carbon intensity (kg CO2/kWh). I did not use scalability or reliability results for CO2.

#      Carbon Data File: 
#      Uses ONLY Performance runtimes (not Scalability/Reliability), 
#      Placed on my Desktop Excel of country intensities "Filtered CO2 intensity 236 Countries.xlsx"
#      (CSV or XLSX; year column optional. I have selected --year-select latest.)
# ----------------------------------------------------------------------------------------------------------------
"""1 Fourier Transform

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/i222070tabidahusmani/1-fourier-transform.a54472c9-abf7-4309-a917-7e07154e1cc3.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20251121/auto/storage/goog4_request%26X-Goog-Date%3D20251121T122103Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D49f4582979b1b02f51dad9149d36e1682cf012cc32e03d9624bd9d6130b04b371cf461cb11f53a4e244a6b468bda04fa46595758efd595401f94905a1222e58c6c17b627291b516e1f78cadb552d4d23ca30c21f69a738723f885c57a7eac8aa25d481fcbba272c3fa763d098c49c878fcf52b71d35e98f7e601f9cfc8698e6764c0a5fc8fba916caee62dc1b42b74813681848083e68f0320def482d1d5694aee74dc9f732f289e04972efbdab8472bc8101f0e9f3d6f22d39f6dbe902efc314b38a55a708742befc807fe6f231778dbe8176204092fae206356f2fdc50e1961fc659f90da351cbb5d07f160d04417aa5ad40466ff2301e0adc28b779cd5370
"""


# ------------********------------ Imports

import os, sys, time, tracemalloc, pathlib, warnings, math
from dataclasses import dataclass
from typing import List, Tuple, Dict, Any
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed

# ------------********------------
# GPU Setup and Dependencies
# ------------********------------

#This section initializes GPU support by attempting to import and validate CuPy for accelerated computation.
#It performs a lightweight runtime check to confirm GPU availability, memory access, and compute capability.
#If CuPy is unavailable or GPU initialization fails, the code gracefully falls back to NumPy on the CPU.
#Status messages are printed to clearly indicate which computational backend is being used.

print("🔍 Checking GPU availability...")

HAS_GPU = False
cp = None

try:
    import cupy as cp
    # Test if GPU is available and working
    with cp.cuda.Device(0):
        # Simple test to verify GPU functionality
        test_array = cp.zeros(10, dtype=cp.float32)
        result = cp.sum(test_array)
        HAS_GPU = True
        print(f"✅ GPU detected: {cp.cuda.runtime.getDeviceProperties(0)['name'].decode()}")
        print(f"   Memory: {cp.cuda.Device().mem_info[1] / 1e9:.2f} GB")
        print(f"   Compute Capability: {cp.cuda.runtime.getDeviceProperties(0)['major']}.{cp.cuda.runtime.getDeviceProperties(0)['minor']}")
except ImportError:
    print("❌ CuPy not available, falling back to NumPy")
    import numpy as cp
except Exception as e:
    print(f"⚠️  GPU setup failed: {e}, falling back to NumPy")
    import numpy as cp

# If GPU failed, use NumPy
if not HAS_GPU:
    import numpy as cp
    print("🔄 Using NumPy (CPU) backend")

# Install required packages
def _ensure(pkgs: List[str]):
    import importlib, subprocess
    missing = []
    for p in pkgs:
        try:
            importlib.import_module(p)
        except ImportError:
            missing.append(p)
    if missing:
        print(f"[setup] Installing missing packages: {missing}")
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *missing])
        except Exception as e:
            print(f"[setup] Auto-install failed: {e}")

_ensure(["pandas", "matplotlib", "openpyxl", "psutil"])

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# ------------********------------

# GPU utility functions
#These helper utilities abstract device identification and resource management for GPU-enabled execution.
#The device query reports whether computation is running on a GPU or CPU with graceful error handling.

def get_device_name() -> str:
    """Get current device name"""
    if HAS_GPU:
        try:
            return f"GPU: {cp.cuda.runtime.getDeviceProperties(0)['name'].decode()}"
        except:
            return "GPU: Unknown"
    return "CPU: NumPy"

#A cleanup routine safely releases GPU memory pools to prevent leaks between runs.

def safe_gpu_cleanup():
    """Safely cleanup GPU memory"""
    if HAS_GPU:
        try:
            cp.get_default_memory_pool().free_all_blocks()
        except:
            pass

# Thread-safe GPU operations
_gpu_lock = threading.Lock()

#A global lock is defined to ensure thread-safe access to shared GPU resources.
def run_experiment_thread_safe(args):
    """
    Thread-safe GPU experiment runner.
    Uses a lock to prevent multiple threads from accessing GPU simultaneously.
    """
    N, steps, acc_tol, seed = args
    with _gpu_lock:  # Ensure only one thread uses GPU at a time
        return _run_single_experiment(N, steps, acc_tol, seed)

# ------------********------------
# ========================= Quantum Fourier Transform Core =========================
# ------------********------------

#This def make_signal_2tone function generates a synthetic one- or two-tone real signal with additive white Gaussian noise.
#It dynamically selects between CuPy and NumPy arrays to support GPU or CPU execution transparently.
#Signal phases and frequencies are randomized, while noise power is scaled to achieve a target SNR.
#Backend-specific random number generation is used to ensure compatibility and performance on each device.

def make_signal_2tone(N: int, rng, snr_db: float = 30.0):
    """Length-N real 2-tone signal with integer bins in [1, N//2-1] + AWGN."""
    if N < 8:
        k1 = rng.integers(1, max(2, N//2))
        true_bins = [int(k1)]
    else:
        k1 = rng.integers(1, N//2)
        k2 = rng.integers(1, N//2 - 1)
        if k2 >= k1: k2 += 1
        true_bins = sorted([int(k1), int(k2)])

    # Use the appropriate array library (CuPy or NumPy)
    n = cp.arange(N, dtype=cp.float64)
    ph1 = rng.uniform(0, 2*cp.pi)
    ph2 = rng.uniform(0, 2*cp.pi)
    x = cp.cos(2*cp.pi*k1*n/N + ph1)
    if len(true_bins) == 2:
        x = x + cp.cos(2*cp.pi*k2*n/N + ph2)

    sig_pow = cp.mean(x**2)
    snr_lin = 10.0**(snr_db/10.0)
    noise_pow = sig_pow / snr_lin

    # Generate noise using the appropriate RNG
    if HAS_GPU:
        # Use CuPy's random for GPU
        noise = cp.random.normal(0.0, cp.sqrt(noise_pow), size=N)
    else:
        # Use NumPy's random for CPU
        noise = rng.normal(0.0, math.sqrt(noise_pow), size=N)
        noise = cp.asarray(noise)

    x = x + noise
    return x, true_bins

#This def topk_one_sided_bins helper extracts the strongest frequency bins from a one-sided spectrum using the active compute backend.
#It computes magnitudes, optionally suppresses the DC component, and ranks bins by descending strength.
#CuPy operations are used for efficiency, with results converted back to host integers for compatibility.

def topk_one_sided_bins(X: cp.ndarray, k: int):
    N = X.shape[0]
    one = X[:N//2+1]
    mag = cp.abs(one)
    if k >= 2 and len(mag) > 0:
        mag = mag.copy(); mag[0] = 0.0  # suppress DC when looking for tones
    idx = cp.argsort(-mag)[:k]
    return sorted(int(i) for i in cp.asnumpy(idx))

#This function evaluates how accurately dominant frequency bins are recovered from a spectral estimate.
#It compares estimated peak locations against known true bins within an optional tolerance.
#The result is returned as a normalized recovery fraction to remain robust for small or degenerate cases.

def accuracy_recovery(X: cp.ndarray, true_bins, tol_bins: int = 0):
    k = len(true_bins)
    est = topk_one_sided_bins(X, k)
    matched = sum(1 for t in true_bins if any(abs(t - e) <= tol_bins for e in est))
    return matched / max(1, k)

#These routines support error measurement and transformation construction for complex-valued signals.
#The RMSE function computes magnitude error while handling GPU and CPU backends appropriately.
def rmse_complex(a: cp.ndarray, b: cp.ndarray) -> float:
    diff = a - b
    if HAS_GPU:
        return float(cp.sqrt(cp.mean((diff.real**2 + diff.imag**2))))
    else:
        return float(np.sqrt(np.mean((cp.asnumpy(diff.real)**2 + cp.asnumpy(diff.imag)**2))))

#The QFT builder creates a fully dense, normalized transform matrix using the active array library.
def qft_dense_matrix(N: int) -> cp.ndarray:
    n = cp.arange(N).reshape(1, N)
    k = cp.arange(N).reshape(N, 1)
    return cp.exp(2j * cp.pi * (k @ n) / N) / math.sqrt(N)

def _run_single_experiment(N: int, steps: int, acc_tol: float, seed: int) -> dict:
    # Use numpy RNG for consistency, but convert all operations to GPU arrays
    rng_np = np.random.default_rng(seed)

    tracemalloc.start()
    t0 = time.perf_counter()

    try:
        # Precompute QFT matrix once for this N
        F = qft_dense_matrix(N)

        accs, rmses = [], []

        for _ in range(steps):
            # Generate signal directly on GPU
            x, true_bins = make_signal_2tone(N, rng_np, snr_db=30.0)

            # Normalize to unit L2 norm
            norm = cp.linalg.norm(x)
            if norm == 0.0:
                x_amp = cp.ones(N, dtype=cp.complex128) / math.sqrt(N)
            else:
                x_amp = (x / norm).astype(cp.complex128)

            # Apply QFT using dense matrix multiplication
            state = F @ x_amp

            # Reference spectrum (matches QFT definition)
            # Use appropriate FFT implementation
            if HAS_GPU:
                # Use CuPy's FFT
                X_ref = cp.fft.ifft(x_amp) * math.sqrt(N)
            else:
                # Use NumPy's FFT
                x_amp_cpu = cp.asnumpy(x_amp)
                X_ref_cpu = np.fft.ifft(x_amp_cpu) * math.sqrt(N)
                X_ref = cp.asarray(X_ref_cpu)

            accs.append(accuracy_recovery(state, true_bins, tol_bins=0))
            rmses.append(rmse_complex(state, X_ref))

        runtime = time.perf_counter() - t0
        _, peak = tracemalloc.get_traced_memory()
        tracemalloc.stop()

        acc_mean = float(cp.mean(cp.asarray(accs))) if accs else 0.0
        rmse_mean = float(cp.mean(cp.asarray(rmses))) if rmses else 0.0

        success = bool(acc_mean >= acc_tol)

    except Exception as e:
        print(f"❌ Experiment failed for N={N}, seed={seed}: {e}")
        runtime = time.perf_counter() - t0
        _, peak = tracemalloc.get_traced_memory()
        tracemalloc.stop()
        acc_mean = 0.0
        rmse_mean = 0.0
        success = False

    # Cleanup GPU memory
    safe_gpu_cleanup()

    return {
        "N": int(N),
        "steps": int(steps),
        "seed": int(seed),
        "accuracy_mean": acc_mean,
        "rmse_vs_fft": rmse_mean,
        "success": success,
        "runtime_s": float(runtime),
        "peak_mem_mb": float(peak / (1024**2)),
        "signals_processed": int(steps),
        "device": get_device_name()
    }
# ------------********------------
# ============================== Carbon I/O ==============================
# ------------********------------

#These utilities handle locating and loading an Excel file containing country-level carbon intensity data.
#The path resolver flexibly checks absolute paths and common desktop locations for user convenience.
def resolve_excel_path(excel_arg: str) -> str:
    p = pathlib.Path(excel_arg)
    if p.is_absolute() and p.exists():
        return str(p)
    desktop = pathlib.Path.home() / "Desktop" / excel_arg
    return str(desktop if desktop.exists() else p)

#The loader function infers relevant columns by name and data type, standardizes them, and optionally selects the latest year.
#It also normalizes units when needed and cleans the dataset by removing missing or invalid entries.
def load_carbon_excel(path: str, year_select: str = "latest") -> pd.DataFrame:
    df = pd.read_excel(path)
    cols = {c.lower(): c for c in df.columns}
    cand_country = next((v for k, v in cols.items() if "country" in k or "nation" in k or k == "location"), None)
    if cand_country is None:
        raise ValueError("No 'Country' column found.")
    cand_year = next((v for k, v in cols.items() if "year" in k or "date" in k), None)
    cand_intensity = next((v for k, v in cols.items()
                           if "intensity" in k or ("co2" in k and "kwh" in k) or "kgco2" in k or "gco2" in k), None)
    if cand_intensity is None:
        numeric_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
        if cand_year in numeric_cols:
            numeric_cols.remove(cand_year)
        if not numeric_cols:
            raise ValueError("No numeric intensity column detected.")
        cand_intensity = numeric_cols[0]
    keep = [cand_country] + ([cand_year] if cand_year else []) + [cand_intensity]
    df = df[keep].copy()
    df.columns = ["Country", "Year", "Intensity"] if len(keep) == 3 else ["Country", "Intensity"]
    if "Year" in df.columns and year_select.lower() == "latest":
        df = df.sort_values(["Country", "Year"]).groupby("Country", as_index=False).tail(1)

    # Heuristic unit fix: if median looks like g/kWh, convert to kg/kWh
    med = float(df["Intensity"].dropna().median())
    if med > 50:
        df["Intensity"] = df["Intensity"] / 1000.0

    return df.dropna(subset=["Country", "Intensity"]).reset_index(drop=True)

#This function estimates total energy consumption and associated carbon emissions from performance measurements.
#It aggregates runtime to compute total energy use, accounting for hardware power draw and data center efficiency.
#The carbon intensity data is combined to estimate per-country emissions and generate summary statistics.
def compute_carbon(perf_df: pd.DataFrame, intensity_df: pd.DataFrame,
                   power_watts: float, pue: float, combine: bool) -> tuple[pd.DataFrame, pd.DataFrame]:
    total_runtime_s = float(perf_df["runtime_s"].sum())
    kWh_total = power_watts * pue * total_runtime_s / 3_600_000.0
    df = intensity_df.copy()
    df["kWh"] = kWh_total
    df["kgCO2e"] = df["Intensity"] * df["kWh"]

    # ALWAYS return country-wise results (ignore combine parameter)
    carbon_output = df.sort_values("kgCO2e", ascending=False)

    summary = pd.DataFrame({
        "total_runtime_s": [total_runtime_s],
        "power_watts": [power_watts],
        "PUE": [pue],
        "kWh_total": [kWh_total],
        "median_intensity_kg_per_kWh": [float(df["Intensity"].median())],
        "mean_kgCO2e_across_countries": [float(df["kgCO2e"].mean())],
        "device": [perf_df["device"].iloc[0] if "device" in perf_df.columns else "Unknown"],
        "combine_mode": [combine],
        "countries_analyzed": [len(df)]
    })
    return carbon_output, summary
# ------------********------------
# ============================== Plot Helpers ==============================
# ------------********------------

#This section defines plotting helpers and visualization routines for summarizing experiment results.
#   It ensures compatibility across Matplotlib versions while configuring consistent figure output settings.
#   The plotting function aggregates results by signal length and generates runtime and accuracy trend figures.
#   Each plot is labeled, styled, and saved to disk for later analysis and reporting.

plt_kwargs = dict(dpi=140, bbox_inches="tight")

def _boxplot_with_labels(data, labels):
    # Matplotlib 3.9 renamed 'labels' -> 'tick_labels'
    try:
        plt.boxplot(data, tick_labels=labels)
    except TypeError:
        plt.boxplot(data, labels=labels)

# ------------********------------
def plot_performance(df: pd.DataFrame, outdir: str):
    """Plot performance metrics"""
    # Runtime vs N
    g = df.groupby("N")["runtime_s"].mean().reset_index()
    plt.figure(figsize=(10, 6))
    plt.plot(g["N"], g["runtime_s"], marker="o", linewidth=2, markersize=8)
    plt.title(f"Performance: Runtime vs Signal Length\n{get_device_name()}")
    plt.xlabel("Signal Length (N)")
    plt.ylabel("Runtime (s)")
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "perf_runtime_vs_N.png"), **plt_kwargs)
    plt.close()

    # Accuracy vs N
    g2 = df.groupby("N")["accuracy_mean"].mean().reset_index()
    plt.figure(figsize=(10, 6))
    plt.plot(g2["N"], g2["accuracy_mean"], marker="s", linewidth=2, markersize=8)
    plt.title(f"Performance: Tone Recovery Accuracy vs Signal Length\n{get_device_name()}")
    plt.xlabel("Signal Length (N)")
    plt.ylabel("Accuracy")
    plt.grid(True, alpha=0.3)
    plt.ylim(0, 1.05)
    plt.savefig(os.path.join(outdir, "perf_accuracy_vs_N.png"), **plt_kwargs)
    plt.close()

    # RMSE vs N
    g3 = df.groupby("N")["rmse_vs_fft"].mean().reset_index()
    plt.figure(figsize=(10, 6))
    plt.plot(g3["N"], g3["rmse_vs_fft"], marker="^", linewidth=2, markersize=8, color='green')
    plt.title(f"Performance: RMSE vs FFT Reference\n{get_device_name()}")
    plt.xlabel("Signal Length (N)")
    plt.ylabel("RMSE")
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "perf_rmse_vs_N.png"), **plt_kwargs)
    plt.close()

# ------------********------------
def plot_scalability(df: pd.DataFrame, outdir: str):
    """Plot scalability metrics"""
    # Runtime scaling with N (log-log)
    g = df.groupby("N")["runtime_s"].mean().reset_index()
    plt.figure(figsize=(10, 6))
    plt.loglog(g["N"], g["runtime_s"], marker="o", markersize=8)
    plt.title(f"Scalability: Runtime vs Signal Length (log-log)\n{get_device_name()}")
    plt.xlabel("Signal Length (N)")
    plt.ylabel("Runtime (s)")
    plt.grid(True, which="both", alpha=0.3)
    plt.savefig(os.path.join(outdir, "scal_loglog_runtime_vs_N.png"), **plt_kwargs)
    plt.close()

    # Memory scaling with N
    g2 = df.groupby("N")["peak_mem_mb"].mean().reset_index()
    plt.figure(figsize=(10, 6))
    plt.plot(g2["N"], g2["peak_mem_mb"], marker="s", linewidth=2, markersize=8, color='red')
    plt.title(f"Scalability: Memory vs Signal Length\n{get_device_name()}")
    plt.xlabel("Signal Length (N)")
    plt.ylabel("Peak Memory (MB)")
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "scal_memory_vs_N.png"), **plt_kwargs)
    plt.close()

# ------------********------------
def plot_reliability(df: pd.DataFrame, outdir: str):
    """Plot reliability metrics"""
    # Accuracy distribution by N
    data = [df[df["N"] == n]["accuracy_mean"].values for n in sorted(df["N"].unique())]
    plt.figure(figsize=(10, 6))
    _boxplot_with_labels(data, labels=sorted(df["N"].unique()))
    plt.title(f"Reliability: Accuracy Distribution by Signal Length\n{get_device_name()}")
    plt.xlabel("Signal Length (N)")
    plt.ylabel("Accuracy")
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "rel_accuracy_distribution.png"), **plt_kwargs)
    plt.close()

    # Success rate trend
    success_rates = df.groupby('N')['success'].mean().reset_index()
    plt.figure(figsize=(10, 6))
    plt.plot(success_rates['N'], success_rates['success'], marker='o', linewidth=2, markersize=8)
    plt.title(f"Reliability: Batch Success Rate vs Signal Length\n{get_device_name()}")
    plt.xlabel("Signal Length (N)")
    plt.ylabel("Batch Success Rate")
    plt.grid(True, alpha=0.3)
    plt.ylim(0, 1.1)
    plt.savefig(os.path.join(outdir, "rel_batch_success.png"), **plt_kwargs)
    plt.close()

# ------------********------------
def plot_carbon(df: pd.DataFrame, combine: bool, outdir: str):
    """Generate carbon footprint plots - ALWAYS country-wise"""
    # Top 15 highest emissions
    top = df.nlargest(15, "kgCO2e")
    plt.figure(figsize=(12, 8))
    plt.barh(top["Country"][::-1], top["kgCO2e"][::-1], color='red', alpha=0.7)
    plt.xlabel("kg CO2e (higher = dirtier grid)", fontsize=12)
    plt.title(f"Carbon: Top 15 Highest Emissions\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(outdir, "carbon_top15.png"), **plt_kwargs)
    plt.close()

    # Bottom 15 lowest emissions
    bot = df.nsmallest(15, "kgCO2e")
    plt.figure(figsize=(12, 8))
    plt.barh(bot["Country"][::-1], bot["kgCO2e"][::-1], color='green', alpha=0.7)
    plt.xlabel("kg CO2e (lower = cleaner grid)", fontsize=12)
    plt.title(f"Carbon: Bottom 15 Lowest Emissions\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(outdir, "carbon_bottom15.png"), **plt_kwargs)
    plt.close()

    # Distribution histogram
    plt.figure(figsize=(10, 6))
    plt.hist(df["kgCO2e"], bins=30, alpha=0.7, edgecolor='black', color='orange')
    plt.xlabel("kg CO2e for this experiment", fontsize=12)
    plt.ylabel("Frequency", fontsize=12)
    plt.title(f"Carbon: Emission Distribution\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "carbon_distribution.png"), **plt_kwargs)
    plt.close()

    # CDF plot
    xs = np.sort(df["kgCO2e"].values)
    ys = np.arange(1, len(xs) + 1) / len(xs)
    plt.figure(figsize=(10, 6))
    plt.plot(xs, ys, linewidth=2, color='purple')
    plt.xlabel("kg CO2e", fontsize=12)
    plt.ylabel("CDF", fontsize=12)
    plt.title(f"Carbon: Cumulative Distribution\n{get_device_name()}", fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(outdir, "carbon_cdf.png"), **plt_kwargs)
    plt.close()

# ------------********------------
# ------------********------------ Utility Functions 
# ------------********------------

#These small utilities handle filesystem setup and structured result export.
#The directory helper safely creates output paths without raising errors if they already exist.
#The Excel writer function saves multiple pandas DataFrames into a single workbook using separate sheets.
def ensure_dir(d: str):
    """Ensure directory exists"""
    os.makedirs(d, exist_ok=True)

def to_excel(dfs: Dict[str, pd.DataFrame], path: str):
    """Save multiple DataFrames to Excel with different sheets"""
    with pd.ExcelWriter(path, engine="openpyxl") as w:
        for name, df in dfs.items():
            df.to_excel(w, index=False, sheet_name=name[:31])

# ------------********------------
# ------------********------------ Main Experiment Runner ==============================
# ------------********------------

def run_qft_experiment():
    """
    Main Quantum Fourier Transform experiment runner with hardcoded parameters for Kaggle.
    """
    # Experiment parameters
    sizes = [64, 128, 256, 512]  # Signal lengths
    trials = 10                   # seeds per N
    steps = 50                    # signals per trial
    acc_tol = 0.9                # accuracy threshold
    method = "qft_signal_processing"
    workers = 4                   # Number of parallel threads

    # Carbon parameters
    device_power_watts = 65.0
    pue = 1.2
    combine = True

    print(f"🚀 Starting Quantum Fourier Transform experiments on {get_device_name()}")
    print(f"🔧 Configuration:")
    print(f"   Signal lengths: {sizes}")
    print(f"   Trials per size: {trials}")
    print(f"   Signals per trial: {steps}")
    print(f"   Accuracy tolerance: {acc_tol}")
    print(f"   Method: {method}")
    print(f"   Workers: {workers}")
    print(f"   Device power: {device_power_watts}W")
    print(f"   PUE: {pue}")
    print(f"   Combine carbon: {combine}")

    # Create output folders
    perf_dir = os.path.join(os.getcwd(), "Performance")
    scal_dir = os.path.join(os.getcwd(), "Scalability")
    rel_dir  = os.path.join(os.getcwd(), "Reliability")
    carb_root = os.path.join(os.getcwd(), "Carbon footprints")
    carb_dir  = os.path.join(carb_root, "carbon_by_country")

    for d in [perf_dir, scal_dir, rel_dir, carb_dir]:
        ensure_dir(d)

    # Prepare jobs
    jobs = []
    for N in sizes:
        for i in range(trials):
            seed = 1000 + 37 * N + i
            jobs.append((N, steps, acc_tol, seed))

    all_rows = []

    def _consume(row):
        """Process completed job results"""
        all_rows.append(row)
        print(f"  ✅ N={row['N']}, seed={row['seed']} "
              f"(runtime={row['runtime_s']:.4f}s, accuracy={row['accuracy_mean']:.3f}, "
              f"RMSE={row['rmse_vs_fft']:.2e}, success={row['success']})")

    # Execute jobs with thread-based parallelization
    print(f"🔀 Running {len(jobs)} jobs in parallel with {workers} threads...")

    if workers > 1 and len(jobs) > 1:
        with ThreadPoolExecutor(max_workers=workers) as executor:
            # Submit all jobs
            future_to_job = {executor.submit(run_experiment_thread_safe, job): job for job in jobs}

            # Collect results as they complete
            for future in as_completed(future_to_job):
                try:
                    result = future.result()
                    _consume(result)
                except Exception as e:
                    job = future_to_job[future]
                    print(f"❌ Job failed N={job[0]}, seed={job[3]}: {e}")
    else:
        # Fallback to sequential execution
        for job in jobs:
            try:
                result = run_experiment_thread_safe(job)
                _consume(result)
            except Exception as e:
                print(f"❌ Job failed N={job[0]}, seed={job[3]}: {e}")

    # Check if we have any successful results
    if not all_rows:
        print("💥 CRITICAL: No experiments completed successfully!")
        return None

    perf_df = pd.DataFrame(all_rows)

# ------------********------------
    # ---------------- Performance Results ----------------
# ------------********------------

    print("📊 Generating Performance results...")
    perf_excel = os.path.join(perf_dir, "performance_results.xlsx")
    perf_agg = perf_df.groupby("N").agg({
        "runtime_s": "mean",
        "accuracy_mean": "mean",
        "rmse_vs_fft": "mean",
        "peak_mem_mb": "mean",
        "success": "mean"
    }).reset_index()

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "raw_runs": perf_df,
            "aggregated": perf_agg
        }, perf_excel)

    plot_performance(perf_df, perf_dir)

# ------------********------------
    # ---------------- Scalability Results ----------------
# ------------********------------

    print("📈 Generating Scalability results...")
    scal_excel = os.path.join(scal_dir, "scalability_results.xlsx")
    scal_agg = perf_df.groupby("N").agg({
        "runtime_s": "mean",
        "peak_mem_mb": "mean",
        "accuracy_mean": "mean"
    }).reset_index()

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "from_perf_runs": perf_df[["N", "seed", "runtime_s", "peak_mem_mb", "accuracy_mean"]],
            "aggregated": scal_agg
        }, scal_excel)

    plot_scalability(perf_df, scal_dir)

# ------------********------------
    # ---------------- Reliability Results ----------------
# ------------********------------

    print("🎯 Generating Reliability results...")
    rel_excel = os.path.join(rel_dir, "reliability_results.xlsx")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "accuracy_analysis": perf_df[["N", "seed", "accuracy_mean", "rmse_vs_fft", "success"]]
        }, rel_excel)

    plot_reliability(perf_df, rel_dir)

# ------------********------------
    # ---------------- Carbon Footprint Results ----------------
# ------------********------------

    print("🌍 Generating Carbon footprint results...")

    # Load carbon data from Kaggle input directory
    excel_path = "/kaggle/input/masters/Filtered CO2 intensity 236 Countries.xlsx"
    intensity_df = None

    try:
        # Try to load from the exact path
        intensity_df = pd.read_excel(excel_path)
        print(f"✅ Loaded carbon data from: {excel_path}")
        print(f"   Columns found: {list(intensity_df.columns)}")
        print(f"   Countries loaded: {len(intensity_df)}")

        # Auto-detect and process columns
        cols = {c.lower(): c for c in intensity_df.columns}
        cand_country = next((v for k,v in cols.items() if "country" in k or "nation" in k or k=="location"), None)
        if cand_country is None:
            raise ValueError("No 'Country' column found.")

        cand_intensity = next((v for k,v in cols.items() if "intensity" in k or ("co2" in k and ("kwh" in k or "/kwh" in k)) or "kgco2" in k or "gco2" in k), None)

        if cand_intensity is None:
            numeric_cols = [c for c in intensity_df.columns if pd.api.types.is_numeric_dtype(intensity_df[c])]
            if not numeric_cols:
                raise ValueError("No numeric intensity column detected.")
            cand_intensity = numeric_cols[0]

        # Keep only necessary columns
        intensity_df = intensity_df[[cand_country, cand_intensity]].copy()
        intensity_df.columns = ["Country", "Intensity"]

        # Convert gCO2/kWh to kgCO2/kWh if needed
        med = float(intensity_df["Intensity"].dropna().median())
        if med > 50:
            intensity_df["Intensity"] = intensity_df["Intensity"] / 1000.0

        intensity_df = intensity_df.dropna(subset=["Country", "Intensity"]).reset_index(drop=True)
        print(f"✅ Processed carbon data for {len(intensity_df)} countries")

    except Exception as e:
        print(f"❌ ERROR loading carbon data: {e}")
        print("💡 Using sample carbon data as fallback...")
        # Create sample data similar to other codes
        countries = ["France", "Sweden", "Norway", "Switzerland", "Austria", "Germany", "United States", "China", "India"]
        intensities = [52, 41, 32, 45, 62, 385, 389, 537, 708]
        intensity_df = pd.DataFrame({
            "Country": countries,
            "Intensity": [i/1000.0 for i in intensities]  # Convert to kg/kWh
        })

    ensure_dir(carb_dir)
    carbon_df, summary_df = compute_carbon(perf_df, intensity_df,
                                           power_watts=device_power_watts,
                                           pue=pue, combine=combine)
    carb_excel = os.path.join(carb_dir, "carbon_results.xlsx")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        to_excel({
            "carbon_results": carbon_df,
            "summary": summary_df,
            "intensity_input": intensity_df,
            "performance_reference": perf_df[["N", "seed", "runtime_s"]]
        }, carb_excel)

    # Generate carbon plots
    plot_carbon(carbon_df, combine, carb_dir)
    print(f"✅ Carbon analysis complete: {len(carbon_df)} entries")

    # Final summary
    print("\n" + "="*60)
    print("🎉 QUANTUM FOURIER TRANSFORM EXPERIMENT COMPLETE - RESULTS SUMMARY")
    print("="*60)
    print(f"📁 Performance:     {perf_excel}")
    print(f"📁 Scalability:     {scal_excel}")
    print(f"📁 Reliability:     {rel_excel}")
    print(f"📁 Carbon:          {carb_excel}")
    print(f"🖥️  Device:          {get_device_name()}")
    print(f"📊 Total runs:      {len(perf_df)}")
    print(f"⚡ Total runtime:   {perf_df['runtime_s'].sum():.2f}s")
    print(f"🔬 Signal lengths:  {sizes}")
    print(f"🎯 Success rate:    {perf_df['success'].mean() * 100:.1f}%")
    print(f"📈 Total signals:   {perf_df['signals_processed'].sum():,}")

    print(f"\n📂 All results saved to:")
    for d in [perf_dir, scal_dir, rel_dir, carb_dir]:
        print(f"   • {d}")

    return perf_df

# ------------********------------
# ------------********------------Main execution for Kaggle
# ------------********------------
if __name__ == "__main__":
    # Clean up GPU state
    safe_gpu_cleanup()

    print("🚀 Starting Quantum Fourier Transform Benchmark on Kaggle")
    print("=" * 50)

    # Run the complete experiment
    results_df = run_qft_experiment()

    if results_df is not None:
        # Display final results summary
        print("\n📊 FINAL RESULTS SUMMARY")
        print("=" * 30)
        print(f"Total experiments: {len(results_df)}")
        print(f"Signal lengths: {sorted(results_df['N'].unique())}")
        print(f"Average runtime: {results_df['runtime_s'].mean():.6f}s")
        print(f"Success rate: {results_df['success'].mean() * 100:.1f}%")
        print(f"Average accuracy: {results_df['accuracy_mean'].mean():.3f}")
        print(f"Total signals processed: {results_df['signals_processed'].sum():,}")
        print(f"Device used: {get_device_name()}")

        # Show folder structure
        print("\n📁 GENERATED OUTPUT STRUCTURE:")
        base_dir = '/kaggle/working'
        for root, dirs, files in os.walk(base_dir):
            # Only show our output directories
            if any(x in root for x in ['Performance', 'Scalability', 'Reliability', 'Carbon footprints']):
                level = root.replace(base_dir, '').count(os.sep)
                indent = ' ' * 2 * level
                print(f'{indent}📁 {os.path.basename(root)}/')
                sub_indent = ' ' * 2 * (level + 1)
                for file in files:
                    if file.endswith(('.xlsx', '.png')):
                        file_path = os.path.join(root, file)
                        size = os.path.getsize(file_path) / 1024  # KB
                        icon = "📊" if file.endswith('.xlsx') else "🖼️"
                        print(f'{sub_indent}{icon} {file} ({size:.1f} KB)')

        print("\n✅ All Quantum Fourier Transform deliverables generated successfully!")
        print("   • Performance/performance_results.xlsx + perf_*.png")
        print("   • Scalability/scalability_results.xlsx + scal_*.png")
        print("   • Reliability/reliability_results.xlsx + rel_*.png")
        print("   • Carbon footprints/carbon_by_country/carbon_results.xlsx + carbon_*.png")
    else:
        print("❌ Quantum Fourier Transform benchmark failed - no results generated")

